from PyQt5 import QtCore, QtGui, QtWidgets


#####################################################################
# NB: 'object' must be 'QtCore.QObject' for pyqtSlot(list) to work  #
#####################################################################
class Ui_mainWindow(object):
    def _cleanup_threads(self):
        # Stop and wait for all running threads
        for thread in getattr(self, "_threads", []):
            if isinstance(thread, QtCore.QThread) and thread.isRunning():
                thread.quit()
                thread.wait()
        self._threads = []

    def closeEvent(self, event):
        # Ensure all threads are stopped on window close
        self._cleanup_threads()
        super().closeEvent(event)

    def setupUi(self, mainWindow):
        #####################################################################
        # section directly copied from pyuic output - do not alter!         #
        #####################################################################
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1077, 857)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.h_splitterMaster = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h_splitterMaster.sizePolicy().hasHeightForWidth())
        self.h_splitterMaster.setSizePolicy(sizePolicy)
        self.h_splitterMaster.setOrientation(QtCore.Qt.Horizontal)
        self.h_splitterMaster.setObjectName("h_splitterMaster")
        self.widgetProj = QtWidgets.QWidget(self.h_splitterMaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetProj.sizePolicy().hasHeightForWidth())
        self.widgetProj.setSizePolicy(sizePolicy)
        self.widgetProj.setMinimumSize(QtCore.QSize(120, 0))
        self.widgetProj.setObjectName("widgetProj")
        self.verticalLayoutProj = QtWidgets.QVBoxLayout(self.widgetProj)
        self.verticalLayoutProj.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayoutProj.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutProj.setObjectName("verticalLayoutProj")
        self.horizontalLayoutProjParseButton = QtWidgets.QHBoxLayout()
        self.horizontalLayoutProjParseButton.setObjectName("horizontalLayoutProjParseButton")
        self.pushButtonParse = QtWidgets.QPushButton(self.widgetProj)
        self.pushButtonParse.setObjectName("pushButtonParse")
        self.horizontalLayoutProjParseButton.addWidget(self.pushButtonParse)
        self.verticalLayoutProj.addLayout(self.horizontalLayoutProjParseButton)
        self.horizontalLayoutProjParseOptions = QtWidgets.QHBoxLayout()
        self.horizontalLayoutProjParseOptions.setObjectName("horizontalLayoutProjParseOptions")
        self.frameParseOptions = QtWidgets.QFrame(self.widgetProj)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameParseOptions.sizePolicy().hasHeightForWidth())
        self.frameParseOptions.setSizePolicy(sizePolicy)
        self.frameParseOptions.setMinimumSize(QtCore.QSize(0, 111))
        self.frameParseOptions.setMaximumSize(QtCore.QSize(16777215, 111))
        self.frameParseOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParseOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParseOptions.setObjectName("frameParseOptions")
        self.checkBox_splitOddEven = QtWidgets.QCheckBox(self.frameParseOptions)
        self.checkBox_splitOddEven.setGeometry(QtCore.QRect(10, 10, 131, 17))
        self.checkBox_splitOddEven.setObjectName("checkBox_splitOddEven")
        self.lineEdit_split_at_time = QtWidgets.QLineEdit(self.frameParseOptions)
        self.lineEdit_split_at_time.setGeometry(QtCore.QRect(80, 40, 41, 25))
        self.lineEdit_split_at_time.setObjectName("lineEdit_split_at_time")
        self.label_splitTime = QtWidgets.QLabel(self.frameParseOptions)
        self.label_splitTime.setGeometry(QtCore.QRect(10, 40, 61, 20))
        self.label_splitTime.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_splitTime.setObjectName("label_splitTime")
        self.label_gain = QtWidgets.QLabel(self.frameParseOptions)
        self.label_gain.setGeometry(QtCore.QRect(10, 70, 61, 20))
        self.label_gain.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_gain.setObjectName("label_gain")
        self.lineEdit_import_gain = QtWidgets.QLineEdit(self.frameParseOptions)
        self.lineEdit_import_gain.setGeometry(QtCore.QRect(80, 70, 41, 25))
        self.lineEdit_import_gain.setObjectName("lineEdit_import_gain")
        self.horizontalLayoutProjParseOptions.addWidget(self.frameParseOptions)
        self.verticalLayoutProj.addLayout(self.horizontalLayoutProjParseOptions)
        self.widgetStim = QtWidgets.QWidget(self.h_splitterMaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetStim.sizePolicy().hasHeightForWidth())
        self.widgetStim.setSizePolicy(sizePolicy)
        self.widgetStim.setMinimumSize(QtCore.QSize(120, 0))
        self.widgetStim.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widgetStim.setObjectName("widgetStim")
        self.verticalLayoutStim = QtWidgets.QVBoxLayout(self.widgetStim)
        self.verticalLayoutStim.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutStim.setObjectName("verticalLayoutStim")
        self.tableStim = QtWidgets.QTableView(self.widgetStim)
        self.tableStim.setEnabled(True)
        self.tableStim.setMinimumSize(QtCore.QSize(100, 0))
        self.tableStim.setObjectName("tableStim")
        self.verticalLayoutStim.addWidget(self.tableStim)
        self.widgetGraphs = QtWidgets.QWidget(self.h_splitterMaster)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetGraphs.sizePolicy().hasHeightForWidth())
        self.widgetGraphs.setSizePolicy(sizePolicy)
        self.widgetGraphs.setMinimumSize(QtCore.QSize(120, 0))
        self.widgetGraphs.setObjectName("widgetGraphs")
        self.verticalLayoutGraphs = QtWidgets.QVBoxLayout(self.widgetGraphs)
        self.verticalLayoutGraphs.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutGraphs.setObjectName("verticalLayoutGraphs")
        self.v_splitterGraphs = QtWidgets.QSplitter(self.widgetGraphs)
        self.v_splitterGraphs.setOrientation(QtCore.Qt.Vertical)
        self.v_splitterGraphs.setObjectName("v_splitterGraphs")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.v_splitterGraphs)
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutMean = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutMean.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutMean.setObjectName("horizontalLayoutMean")
        self.graphMean = QtWidgets.QWidget(self.horizontalLayoutWidget)
        self.graphMean.setMinimumSize(QtCore.QSize(100, 100))
        self.graphMean.setObjectName("graphMean")
        self.horizontalLayoutMean.addWidget(self.graphMean)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.v_splitterGraphs)
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayoutEvent = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayoutEvent.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutEvent.setObjectName("horizontalLayoutEvent")
        self.graphEvent = QtWidgets.QWidget(self.horizontalLayoutWidget_2)
        self.graphEvent.setMinimumSize(QtCore.QSize(100, 100))
        self.graphEvent.setObjectName("graphEvent")
        self.horizontalLayoutEvent.addWidget(self.graphEvent)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.v_splitterGraphs)
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayoutOutput = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayoutOutput.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutOutput.setObjectName("horizontalLayoutOutput")
        self.graphOutput = QtWidgets.QWidget(self.horizontalLayoutWidget_3)
        self.graphOutput.setMinimumSize(QtCore.QSize(100, 100))
        self.graphOutput.setObjectName("graphOutput")
        self.horizontalLayoutOutput.addWidget(self.graphOutput)
        self.verticalLayoutGraphs.addWidget(self.v_splitterGraphs)
        self.scrollAreaTools = QtWidgets.QScrollArea(self.h_splitterMaster)
        self.scrollAreaTools.setMinimumSize(QtCore.QSize(210, 0))
        self.scrollAreaTools.setMaximumSize(QtCore.QSize(210, 16777215))
        self.scrollAreaTools.setWidgetResizable(True)
        self.scrollAreaTools.setObjectName("scrollAreaTools")
        self.scrollAreaWidgetContentsTools = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsTools.setGeometry(QtCore.QRect(0, -733, 191, 1502))
        self.scrollAreaWidgetContentsTools.setMinimumSize(QtCore.QSize(100, 0))
        self.scrollAreaWidgetContentsTools.setObjectName("scrollAreaWidgetContentsTools")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContentsTools)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frameToolStim = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolStim.sizePolicy().hasHeightForWidth())
        self.frameToolStim.setSizePolicy(sizePolicy)
        self.frameToolStim.setMinimumSize(QtCore.QSize(201, 151))
        self.frameToolStim.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolStim.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolStim.setObjectName("frameToolStim")
        self.checkBox_timepoints_per_stim = QtWidgets.QCheckBox(self.frameToolStim)
        self.checkBox_timepoints_per_stim.setGeometry(QtCore.QRect(10, 30, 161, 23))
        self.checkBox_timepoints_per_stim.setObjectName("checkBox_timepoints_per_stim")
        self.label_stims = QtWidgets.QLabel(self.frameToolStim)
        self.label_stims.setGeometry(QtCore.QRect(10, 10, 62, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_stims.setFont(font)
        self.label_stims.setObjectName("label_stims")
        self.pushButton_stim_add = QtWidgets.QPushButton(self.frameToolStim)
        self.pushButton_stim_add.setGeometry(QtCore.QRect(20, 120, 61, 25))
        self.pushButton_stim_add.setObjectName("pushButton_stim_add")
        self.label_mean_to = QtWidgets.QLabel(self.frameToolStim)
        self.label_mean_to.setGeometry(QtCore.QRect(90, 80, 21, 20))
        self.label_mean_to.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_mean_to.setObjectName("label_mean_to")
        self.lineEdit_mean_selection_end = QtWidgets.QLineEdit(self.frameToolStim)
        self.lineEdit_mean_selection_end.setGeometry(QtCore.QRect(100, 80, 61, 25))
        self.lineEdit_mean_selection_end.setObjectName("lineEdit_mean_selection_end")
        self.label_mean_selected_range = QtWidgets.QLabel(self.frameToolStim)
        self.label_mean_selected_range.setGeometry(QtCore.QRect(10, 60, 81, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_mean_selected_range.setFont(font)
        self.label_mean_selected_range.setObjectName("label_mean_selected_range")
        self.lineEdit_mean_selection_start = QtWidgets.QLineEdit(self.frameToolStim)
        self.lineEdit_mean_selection_start.setGeometry(QtCore.QRect(20, 80, 61, 25))
        self.lineEdit_mean_selection_start.setObjectName("lineEdit_mean_selection_start")
        self.pushButton_stim_remove = QtWidgets.QPushButton(self.frameToolStim)
        self.pushButton_stim_remove.setGeometry(QtCore.QRect(90, 120, 61, 25))
        self.pushButton_stim_remove.setObjectName("pushButton_stim_remove")
        self.pushButton_hide_stim = QtWidgets.QPushButton(self.frameToolStim)
        self.pushButton_hide_stim.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_stim.setFlat(True)
        self.pushButton_hide_stim.setObjectName("pushButton_hide_stim")
        self.checkBox_timepoints_per_stim.raise_()
        self.label_stims.raise_()
        self.pushButton_stim_add.raise_()
        self.label_mean_to.raise_()
        self.label_mean_selected_range.raise_()
        self.pushButton_stim_remove.raise_()
        self.lineEdit_mean_selection_start.raise_()
        self.lineEdit_mean_selection_end.raise_()
        self.pushButton_hide_stim.raise_()
        self.verticalLayout_2.addWidget(self.frameToolStim)
        self.frameToolSweeps = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolSweeps.sizePolicy().hasHeightForWidth())
        self.frameToolSweeps.setSizePolicy(sizePolicy)
        self.frameToolSweeps.setMinimumSize(QtCore.QSize(201, 111))
        self.frameToolSweeps.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolSweeps.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolSweeps.setObjectName("frameToolSweeps")
        self.pushButton_sweeps_even = QtWidgets.QPushButton(self.frameToolSweeps)
        self.pushButton_sweeps_even.setGeometry(QtCore.QRect(60, 70, 41, 25))
        self.pushButton_sweeps_even.setObjectName("pushButton_sweeps_even")
        self.label_sweeps = QtWidgets.QLabel(self.frameToolSweeps)
        self.label_sweeps.setGeometry(QtCore.QRect(10, 10, 151, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_sweeps.setFont(font)
        self.label_sweeps.setObjectName("label_sweeps")
        self.pushButton_sweeps_odd = QtWidgets.QPushButton(self.frameToolSweeps)
        self.pushButton_sweeps_odd.setGeometry(QtCore.QRect(120, 70, 41, 25))
        self.pushButton_sweeps_odd.setObjectName("pushButton_sweeps_odd")
        self.lineEdit_sweeps_range_to = QtWidgets.QLineEdit(self.frameToolSweeps)
        self.lineEdit_sweeps_range_to.setGeometry(QtCore.QRect(120, 30, 41, 25))
        self.lineEdit_sweeps_range_to.setObjectName("lineEdit_sweeps_range_to")
        self.label_sweeps_dash = QtWidgets.QLabel(self.frameToolSweeps)
        self.label_sweeps_dash.setGeometry(QtCore.QRect(110, 30, 16, 20))
        self.label_sweeps_dash.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_sweeps_dash.setObjectName("label_sweeps_dash")
        self.label_sweeps_selection = QtWidgets.QLabel(self.frameToolSweeps)
        self.label_sweeps_selection.setGeometry(QtCore.QRect(10, 30, 41, 20))
        self.label_sweeps_selection.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_sweeps_selection.setObjectName("label_sweeps_selection")
        self.lineEdit_sweeps_range_from = QtWidgets.QLineEdit(self.frameToolSweeps)
        self.lineEdit_sweeps_range_from.setGeometry(QtCore.QRect(60, 30, 41, 25))
        self.lineEdit_sweeps_range_from.setObjectName("lineEdit_sweeps_range_from")
        self.pushButton_hide_sweeps = QtWidgets.QPushButton(self.frameToolSweeps)
        self.pushButton_hide_sweeps.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_sweeps.setFlat(True)
        self.pushButton_hide_sweeps.setObjectName("pushButton_hide_sweeps")
        self.label_sweeps_dash.raise_()
        self.pushButton_sweeps_even.raise_()
        self.label_sweeps.raise_()
        self.pushButton_sweeps_odd.raise_()
        self.lineEdit_sweeps_range_to.raise_()
        self.label_sweeps_selection.raise_()
        self.lineEdit_sweeps_range_from.raise_()
        self.pushButton_hide_sweeps.raise_()
        self.verticalLayout_2.addWidget(self.frameToolSweeps)
        self.frameToolTag = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolTag.sizePolicy().hasHeightForWidth())
        self.frameToolTag.setSizePolicy(sizePolicy)
        self.frameToolTag.setMinimumSize(QtCore.QSize(201, 101))
        self.frameToolTag.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolTag.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolTag.setObjectName("frameToolTag")
        self.pushButton_add_to_set = QtWidgets.QPushButton(self.frameToolTag)
        self.pushButton_add_to_set.setGeometry(QtCore.QRect(20, 30, 101, 25))
        self.pushButton_add_to_set.setObjectName("pushButton_add_to_set")
        self.label_tag = QtWidgets.QLabel(self.frameToolTag)
        self.label_tag.setGeometry(QtCore.QRect(10, 10, 151, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_tag.setFont(font)
        self.label_tag.setObjectName("label_tag")
        self.pushButton_hide_tag = QtWidgets.QPushButton(self.frameToolTag)
        self.pushButton_hide_tag.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_tag.setFlat(True)
        self.pushButton_hide_tag.setObjectName("pushButton_hide_tag")
        self.checkBox_is_group_sample = QtWidgets.QCheckBox(self.frameToolTag)
        self.checkBox_is_group_sample.setGeometry(QtCore.QRect(20, 60, 141, 23))
        self.checkBox_is_group_sample.setObjectName("checkBox_is_group_sample")
        self.verticalLayout_2.addWidget(self.frameToolTag)
        self.verticalLayoutTestSet = QtWidgets.QVBoxLayout()
        self.verticalLayoutTestSet.setObjectName("verticalLayoutTestSet")
        self.verticalLayout_2.addLayout(self.verticalLayoutTestSet)
        self.frameToolBin = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolBin.sizePolicy().hasHeightForWidth())
        self.frameToolBin.setSizePolicy(sizePolicy)
        self.frameToolBin.setMinimumSize(QtCore.QSize(201, 71))
        self.frameToolBin.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolBin.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolBin.setObjectName("frameToolBin")
        self.label_bins = QtWidgets.QLabel(self.frameToolBin)
        self.label_bins.setGeometry(QtCore.QRect(10, 10, 62, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_bins.setFont(font)
        self.label_bins.setObjectName("label_bins")
        self.lineEdit_bin_size = QtWidgets.QLineEdit(self.frameToolBin)
        self.lineEdit_bin_size.setGeometry(QtCore.QRect(20, 30, 61, 25))
        self.lineEdit_bin_size.setObjectName("lineEdit_bin_size")
        self.label_bin_zero_means_off = QtWidgets.QLabel(self.frameToolBin)
        self.label_bin_zero_means_off.setGeometry(QtCore.QRect(100, 30, 81, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(False)
        font.setWeight(50)
        self.label_bin_zero_means_off.setFont(font)
        self.label_bin_zero_means_off.setObjectName("label_bin_zero_means_off")
        self.pushButton_hide_bin = QtWidgets.QPushButton(self.frameToolBin)
        self.pushButton_hide_bin.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_bin.setFlat(True)
        self.pushButton_hide_bin.setObjectName("pushButton_hide_bin")
        self.verticalLayout_2.addWidget(self.frameToolBin)
        self.frameToolType = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        self.frameToolType.setMinimumSize(QtCore.QSize(201, 101))
        self.frameToolType.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolType.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolType.setObjectName("frameToolType")
        self.label_experiment_type = QtWidgets.QLabel(self.frameToolType)
        self.label_experiment_type.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_experiment_type.setFont(font)
        self.label_experiment_type.setObjectName("label_experiment_type")
        self.radioButton_type_time = QtWidgets.QRadioButton(self.frameToolType)
        self.radioButton_type_time.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.radioButton_type_time.setObjectName("radioButton_type_time")
        self.buttonGroup_type = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_type.setObjectName("buttonGroup_type")
        self.buttonGroup_type.addButton(self.radioButton_type_time)
        self.radioButton_type_train = QtWidgets.QRadioButton(self.frameToolType)
        self.radioButton_type_train.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.radioButton_type_train.setObjectName("radioButton_type_train")
        self.buttonGroup_type.addButton(self.radioButton_type_train)
        self.radioButton_type_io = QtWidgets.QRadioButton(self.frameToolType)
        self.radioButton_type_io.setGeometry(QtCore.QRect(100, 50, 82, 17))
        self.radioButton_type_io.setObjectName("radioButton_type_io")
        self.buttonGroup_type.addButton(self.radioButton_type_io)
        self.pushButton_hide_type = QtWidgets.QPushButton(self.frameToolType)
        self.pushButton_hide_type.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_type.setFlat(True)
        self.pushButton_hide_type.setObjectName("pushButton_hide_type")
        self.radioButton_type_sweep = QtWidgets.QRadioButton(self.frameToolType)
        self.radioButton_type_sweep.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.radioButton_type_sweep.setObjectName("radioButton_type_sweep")
        self.buttonGroup_type.addButton(self.radioButton_type_sweep)
        self.radioButton_type_timestamp = QtWidgets.QRadioButton(self.frameToolType)
        self.radioButton_type_timestamp.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.radioButton_type_timestamp.setObjectName("radioButton_type_timestamp")
        self.buttonGroup_type.addButton(self.radioButton_type_timestamp)
        self.radioButton_type_pp = QtWidgets.QRadioButton(self.frameToolType)
        self.radioButton_type_pp.setGeometry(QtCore.QRect(100, 70, 82, 17))
        self.radioButton_type_pp.setObjectName("radioButton_type_pp")
        self.buttonGroup_type.addButton(self.radioButton_type_pp)
        self.verticalLayout_2.addWidget(self.frameToolType)
        self.frameToolType_io = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        self.frameToolType_io.setMinimumSize(QtCore.QSize(201, 121))
        self.frameToolType_io.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolType_io.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolType_io.setObjectName("frameToolType_io")
        self.label_io_input = QtWidgets.QLabel(self.frameToolType_io)
        self.label_io_input.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_io_input.setFont(font)
        self.label_io_input.setObjectName("label_io_input")
        self.radioButton_io_vamp = QtWidgets.QRadioButton(self.frameToolType_io)
        self.radioButton_io_vamp.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.radioButton_io_vamp.setObjectName("radioButton_io_vamp")
        self.buttonGroup_io_i = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_io_i.setObjectName("buttonGroup_io_i")
        self.buttonGroup_io_i.addButton(self.radioButton_io_vamp)
        self.radioButton_io_EPSPamp = QtWidgets.QRadioButton(self.frameToolType_io)
        self.radioButton_io_EPSPamp.setGeometry(QtCore.QRect(100, 30, 82, 17))
        self.radioButton_io_EPSPamp.setObjectName("radioButton_io_EPSPamp")
        self.buttonGroup_io_o = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_io_o.setObjectName("buttonGroup_io_o")
        self.buttonGroup_io_o.addButton(self.radioButton_io_EPSPamp)
        self.radioButton_io_EPSPslope = QtWidgets.QRadioButton(self.frameToolType_io)
        self.radioButton_io_EPSPslope.setGeometry(QtCore.QRect(100, 50, 82, 17))
        self.radioButton_io_EPSPslope.setObjectName("radioButton_io_EPSPslope")
        self.buttonGroup_io_o.addButton(self.radioButton_io_EPSPslope)
        self.radioButton_io_vslope = QtWidgets.QRadioButton(self.frameToolType_io)
        self.radioButton_io_vslope.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.radioButton_io_vslope.setObjectName("radioButton_io_vslope")
        self.buttonGroup_io_i.addButton(self.radioButton_io_vslope)
        self.radioButton_io_stim = QtWidgets.QRadioButton(self.frameToolType_io)
        self.radioButton_io_stim.setGeometry(QtCore.QRect(10, 70, 91, 17))
        self.radioButton_io_stim.setObjectName("radioButton_io_stim")
        self.buttonGroup_io_i.addButton(self.radioButton_io_stim)
        self.label_io_output = QtWidgets.QLabel(self.frameToolType_io)
        self.label_io_output.setGeometry(QtCore.QRect(100, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_io_output.setFont(font)
        self.label_io_output.setObjectName("label_io_output")
        self.checkBox_io_trendline = QtWidgets.QCheckBox(self.frameToolType_io)
        self.checkBox_io_trendline.setGeometry(QtCore.QRect(10, 90, 71, 23))
        self.checkBox_io_trendline.setObjectName("checkBox_io_trendline")
        self.checkBox_io_force0 = QtWidgets.QCheckBox(self.frameToolType_io)
        self.checkBox_io_force0.setGeometry(QtCore.QRect(100, 90, 71, 23))
        self.checkBox_io_force0.setObjectName("checkBox_io_force0")
        self.verticalLayout_2.addWidget(self.frameToolType_io)
        self.frameToolFilter = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        self.frameToolFilter.setMinimumSize(QtCore.QSize(201, 61))
        self.frameToolFilter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolFilter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolFilter.setObjectName("frameToolFilter")
        self.label_filter = QtWidgets.QLabel(self.frameToolFilter)
        self.label_filter.setGeometry(QtCore.QRect(10, 10, 62, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_filter.setFont(font)
        self.label_filter.setObjectName("label_filter")
        self.radioButton_filter_none = QtWidgets.QRadioButton(self.frameToolFilter)
        self.radioButton_filter_none.setGeometry(QtCore.QRect(10, 30, 82, 17))
        self.radioButton_filter_none.setObjectName("radioButton_filter_none")
        self.buttonGroup_filter = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_filter.setObjectName("buttonGroup_filter")
        self.buttonGroup_filter.addButton(self.radioButton_filter_none)
        self.radioButton_filter_savgol = QtWidgets.QRadioButton(self.frameToolFilter)
        self.radioButton_filter_savgol.setGeometry(QtCore.QRect(90, 30, 82, 17))
        self.radioButton_filter_savgol.setObjectName("radioButton_filter_savgol")
        self.buttonGroup_filter.addButton(self.radioButton_filter_savgol)
        self.pushButton_hide_filter = QtWidgets.QPushButton(self.frameToolFilter)
        self.pushButton_hide_filter.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_filter.setFlat(True)
        self.pushButton_hide_filter.setObjectName("pushButton_hide_filter")
        self.verticalLayout_2.addWidget(self.frameToolFilter)
        self.frameToolFilterSavgol = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        self.frameToolFilterSavgol.setMinimumSize(QtCore.QSize(201, 71))
        self.frameToolFilterSavgol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolFilterSavgol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolFilterSavgol.setObjectName("frameToolFilterSavgol")
        self.label_filter_savgol = QtWidgets.QLabel(self.frameToolFilterSavgol)
        self.label_filter_savgol.setGeometry(QtCore.QRect(10, 10, 62, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_filter_savgol.setFont(font)
        self.label_filter_savgol.setObjectName("label_filter_savgol")
        self.label_savgol_window = QtWidgets.QLabel(self.frameToolFilterSavgol)
        self.label_savgol_window.setGeometry(QtCore.QRect(20, 30, 41, 20))
        self.label_savgol_window.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_savgol_window.setObjectName("label_savgol_window")
        self.label_savgol_poly = QtWidgets.QLabel(self.frameToolFilterSavgol)
        self.label_savgol_poly.setGeometry(QtCore.QRect(110, 30, 31, 20))
        self.label_savgol_poly.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_savgol_poly.setObjectName("label_savgol_poly")
        self.lineEdit_savgol_window = QtWidgets.QLineEdit(self.frameToolFilterSavgol)
        self.lineEdit_savgol_window.setGeometry(QtCore.QRect(70, 30, 31, 25))
        self.lineEdit_savgol_window.setObjectName("lineEdit_savgol_window")
        self.lineEdit_savgol_poly = QtWidgets.QLineEdit(self.frameToolFilterSavgol)
        self.lineEdit_savgol_poly.setGeometry(QtCore.QRect(140, 30, 21, 25))
        self.lineEdit_savgol_poly.setObjectName("lineEdit_savgol_poly")
        self.verticalLayout_2.addWidget(self.frameToolFilterSavgol)
        self.frameToolYscale = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolYscale.sizePolicy().hasHeightForWidth())
        self.frameToolYscale.setSizePolicy(sizePolicy)
        self.frameToolYscale.setMinimumSize(QtCore.QSize(201, 111))
        self.frameToolYscale.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolYscale.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolYscale.setObjectName("frameToolYscale")
        self.lineEdit_norm_EPSP_end = QtWidgets.QLineEdit(self.frameToolYscale)
        self.lineEdit_norm_EPSP_end.setGeometry(QtCore.QRect(80, 70, 41, 25))
        self.lineEdit_norm_EPSP_end.setObjectName("lineEdit_norm_EPSP_end")
        self.label_norm_on_sweep = QtWidgets.QLabel(self.frameToolYscale)
        self.label_norm_on_sweep.setGeometry(QtCore.QRect(10, 50, 131, 20))
        self.label_norm_on_sweep.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_norm_on_sweep.setObjectName("label_norm_on_sweep")
        self.checkBox_norm_EPSP = QtWidgets.QCheckBox(self.frameToolYscale)
        self.checkBox_norm_EPSP.setGeometry(QtCore.QRect(10, 30, 111, 23))
        self.checkBox_norm_EPSP.setObjectName("checkBox_norm_EPSP")
        self.label_relative_to = QtWidgets.QLabel(self.frameToolYscale)
        self.label_relative_to.setGeometry(QtCore.QRect(70, 70, 21, 20))
        self.label_relative_to.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_relative_to.setObjectName("label_relative_to")
        self.label_y_axis = QtWidgets.QLabel(self.frameToolYscale)
        self.label_y_axis.setGeometry(QtCore.QRect(10, 10, 81, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_y_axis.setFont(font)
        self.label_y_axis.setObjectName("label_y_axis")
        self.lineEdit_norm_EPSP_start = QtWidgets.QLineEdit(self.frameToolYscale)
        self.lineEdit_norm_EPSP_start.setGeometry(QtCore.QRect(20, 70, 41, 25))
        self.lineEdit_norm_EPSP_start.setObjectName("lineEdit_norm_EPSP_start")
        self.checkBox_output_ymin0 = QtWidgets.QCheckBox(self.frameToolYscale)
        self.checkBox_output_ymin0.setGeometry(QtCore.QRect(80, 30, 111, 23))
        self.checkBox_output_ymin0.setObjectName("checkBox_output_ymin0")
        self.pushButton_hide_y_axis = QtWidgets.QPushButton(self.frameToolYscale)
        self.pushButton_hide_y_axis.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_y_axis.setFlat(True)
        self.pushButton_hide_y_axis.setObjectName("pushButton_hide_y_axis")
        self.label_norm_on_sweep.raise_()
        self.checkBox_norm_EPSP.raise_()
        self.label_relative_to.raise_()
        self.label_y_axis.raise_()
        self.checkBox_output_ymin0.raise_()
        self.lineEdit_norm_EPSP_end.raise_()
        self.lineEdit_norm_EPSP_start.raise_()
        self.pushButton_hide_y_axis.raise_()
        self.verticalLayout_2.addWidget(self.frameToolYscale)
        self.frameToolAspect = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolAspect.sizePolicy().hasHeightForWidth())
        self.frameToolAspect.setSizePolicy(sizePolicy)
        self.frameToolAspect.setMinimumSize(QtCore.QSize(201, 121))
        self.frameToolAspect.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolAspect.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolAspect.setObjectName("frameToolAspect")
        self.checkBox_EPSP_slope = QtWidgets.QCheckBox(self.frameToolAspect)
        self.checkBox_EPSP_slope.setGeometry(QtCore.QRect(10, 30, 101, 23))
        self.checkBox_EPSP_slope.setObjectName("checkBox_EPSP_slope")
        self.checkBox_volley_slope = QtWidgets.QCheckBox(self.frameToolAspect)
        self.checkBox_volley_slope.setGeometry(QtCore.QRect(10, 70, 101, 23))
        self.checkBox_volley_slope.setObjectName("checkBox_volley_slope")
        self.checkBox_EPSP_amp = QtWidgets.QCheckBox(self.frameToolAspect)
        self.checkBox_EPSP_amp.setGeometry(QtCore.QRect(10, 50, 101, 23))
        self.checkBox_EPSP_amp.setObjectName("checkBox_EPSP_amp")
        self.label_aspect = QtWidgets.QLabel(self.frameToolAspect)
        self.label_aspect.setGeometry(QtCore.QRect(10, 10, 62, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_aspect.setFont(font)
        self.label_aspect.setObjectName("label_aspect")
        self.checkBox_volley_amp = QtWidgets.QCheckBox(self.frameToolAspect)
        self.checkBox_volley_amp.setGeometry(QtCore.QRect(10, 90, 101, 23))
        self.checkBox_volley_amp.setObjectName("checkBox_volley_amp")
        self.checkBox_volley_slope_mean = QtWidgets.QCheckBox(self.frameToolAspect)
        self.checkBox_volley_slope_mean.setGeometry(QtCore.QRect(120, 70, 101, 23))
        self.checkBox_volley_slope_mean.setObjectName("checkBox_volley_slope_mean")
        self.checkBox_volley_amp_mean = QtWidgets.QCheckBox(self.frameToolAspect)
        self.checkBox_volley_amp_mean.setGeometry(QtCore.QRect(120, 90, 61, 23))
        self.checkBox_volley_amp_mean.setObjectName("checkBox_volley_amp_mean")
        self.pushButton_hide_aspect = QtWidgets.QPushButton(self.frameToolAspect)
        self.pushButton_hide_aspect.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_aspect.setFlat(True)
        self.pushButton_hide_aspect.setObjectName("pushButton_hide_aspect")
        self.verticalLayout_2.addWidget(self.frameToolAspect)
        self.frameToolAspectSlope = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolAspectSlope.sizePolicy().hasHeightForWidth())
        self.frameToolAspectSlope.setSizePolicy(sizePolicy)
        self.frameToolAspectSlope.setMinimumSize(QtCore.QSize(201, 71))
        self.frameToolAspectSlope.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolAspectSlope.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolAspectSlope.setObjectName("frameToolAspectSlope")
        self.lineEdit_volley_slope_width = QtWidgets.QLineEdit(self.frameToolAspectSlope)
        self.lineEdit_volley_slope_width.setGeometry(QtCore.QRect(140, 30, 31, 25))
        self.lineEdit_volley_slope_width.setObjectName("lineEdit_volley_slope_width")
        self.label_volley_slope_width = QtWidgets.QLabel(self.frameToolAspectSlope)
        self.label_volley_slope_width.setGeometry(QtCore.QRect(100, 30, 31, 20))
        self.label_volley_slope_width.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_volley_slope_width.setObjectName("label_volley_slope_width")
        self.lineEdit_EPSP_slope_width = QtWidgets.QLineEdit(self.frameToolAspectSlope)
        self.lineEdit_EPSP_slope_width.setGeometry(QtCore.QRect(60, 30, 31, 25))
        self.lineEdit_EPSP_slope_width.setObjectName("lineEdit_EPSP_slope_width")
        self.label_EPSP_slope_width = QtWidgets.QLabel(self.frameToolAspectSlope)
        self.label_EPSP_slope_width.setGeometry(QtCore.QRect(20, 30, 31, 20))
        self.label_EPSP_slope_width.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_EPSP_slope_width.setObjectName("label_EPSP_slope_width")
        self.label_header_slope_width = QtWidgets.QLabel(self.frameToolAspectSlope)
        self.label_header_slope_width.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_header_slope_width.setFont(font)
        self.label_header_slope_width.setObjectName("label_header_slope_width")
        self.pushButton_hide_slope_width = QtWidgets.QPushButton(self.frameToolAspectSlope)
        self.pushButton_hide_slope_width.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_slope_width.setFlat(True)
        self.pushButton_hide_slope_width.setObjectName("pushButton_hide_slope_width")
        self.verticalLayout_2.addWidget(self.frameToolAspectSlope)
        self.frameToolAspectAmp = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolAspectAmp.sizePolicy().hasHeightForWidth())
        self.frameToolAspectAmp.setSizePolicy(sizePolicy)
        self.frameToolAspectAmp.setMinimumSize(QtCore.QSize(201, 71))
        self.frameToolAspectAmp.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolAspectAmp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolAspectAmp.setObjectName("frameToolAspectAmp")
        self.lineEdit_volley_amp_halfwidth = QtWidgets.QLineEdit(self.frameToolAspectAmp)
        self.lineEdit_volley_amp_halfwidth.setGeometry(QtCore.QRect(140, 30, 31, 25))
        self.lineEdit_volley_amp_halfwidth.setObjectName("lineEdit_volley_amp_halfwidth")
        self.label_volley_amp_halfwidth = QtWidgets.QLabel(self.frameToolAspectAmp)
        self.label_volley_amp_halfwidth.setGeometry(QtCore.QRect(100, 30, 31, 20))
        self.label_volley_amp_halfwidth.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_volley_amp_halfwidth.setObjectName("label_volley_amp_halfwidth")
        self.lineEdit_EPSP_amp_halfwidth = QtWidgets.QLineEdit(self.frameToolAspectAmp)
        self.lineEdit_EPSP_amp_halfwidth.setGeometry(QtCore.QRect(60, 30, 31, 25))
        self.lineEdit_EPSP_amp_halfwidth.setObjectName("lineEdit_EPSP_amp_halfwidth")
        self.label_EPSP_amp_halfwidth = QtWidgets.QLabel(self.frameToolAspectAmp)
        self.label_EPSP_amp_halfwidth.setGeometry(QtCore.QRect(20, 30, 31, 20))
        self.label_EPSP_amp_halfwidth.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft)
        self.label_EPSP_amp_halfwidth.setObjectName("label_EPSP_amp_halfwidth")
        self.label_header_amp_halfwidth = QtWidgets.QLabel(self.frameToolAspectAmp)
        self.label_header_amp_halfwidth.setGeometry(QtCore.QRect(10, 10, 201, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_header_amp_halfwidth.setFont(font)
        self.label_header_amp_halfwidth.setObjectName("label_header_amp_halfwidth")
        self.pushButton_hide_amplitude_width = QtWidgets.QPushButton(self.frameToolAspectAmp)
        self.pushButton_hide_amplitude_width.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_amplitude_width.setFlat(True)
        self.pushButton_hide_amplitude_width.setObjectName("pushButton_hide_amplitude_width")
        self.verticalLayout_2.addWidget(self.frameToolAspectAmp)
        self.frameToolTest = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolTest.sizePolicy().hasHeightForWidth())
        self.frameToolTest.setSizePolicy(sizePolicy)
        self.frameToolTest.setMinimumSize(QtCore.QSize(201, 111))
        self.frameToolTest.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolTest.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolTest.setObjectName("frameToolTest")
        self.label_test = QtWidgets.QLabel(self.frameToolTest)
        self.label_test.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_test.setFont(font)
        self.label_test.setObjectName("label_test")
        self.pushButton_hide_test = QtWidgets.QPushButton(self.frameToolTest)
        self.pushButton_hide_test.setGeometry(QtCore.QRect(150, 10, 21, 21))
        self.pushButton_hide_test.setFlat(True)
        self.pushButton_hide_test.setObjectName("pushButton_hide_test")
        self.radioButton_test_t = QtWidgets.QRadioButton(self.frameToolTest)
        self.radioButton_test_t.setGeometry(QtCore.QRect(10, 30, 101, 17))
        self.radioButton_test_t.setObjectName("radioButton_test_t")
        self.buttonGroup_test = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_test.setObjectName("buttonGroup_test")
        self.buttonGroup_test.addButton(self.radioButton_test_t)
        self.radioButton_test_anova = QtWidgets.QRadioButton(self.frameToolTest)
        self.radioButton_test_anova.setGeometry(QtCore.QRect(10, 50, 91, 17))
        self.radioButton_test_anova.setObjectName("radioButton_test_anova")
        self.buttonGroup_test.addButton(self.radioButton_test_anova)
        self.radioButton_test_wilcoxon = QtWidgets.QRadioButton(self.frameToolTest)
        self.radioButton_test_wilcoxon.setGeometry(QtCore.QRect(80, 30, 91, 17))
        self.radioButton_test_wilcoxon.setObjectName("radioButton_test_wilcoxon")
        self.buttonGroup_test.addButton(self.radioButton_test_wilcoxon)
        self.radioButton_test_friedman = QtWidgets.QRadioButton(self.frameToolTest)
        self.radioButton_test_friedman.setGeometry(QtCore.QRect(80, 50, 91, 17))
        self.radioButton_test_friedman.setObjectName("radioButton_test_friedman")
        self.buttonGroup_test.addButton(self.radioButton_test_friedman)
        self.radioButton_test_cluster = QtWidgets.QRadioButton(self.frameToolTest)
        self.radioButton_test_cluster.setGeometry(QtCore.QRect(80, 70, 141, 17))
        self.radioButton_test_cluster.setObjectName("radioButton_test_cluster")
        self.buttonGroup_test.addButton(self.radioButton_test_cluster)
        self.checkBox_test_fdr = QtWidgets.QCheckBox(self.frameToolTest)
        self.checkBox_test_fdr.setGeometry(QtCore.QRect(10, 90, 141, 23))
        self.checkBox_test_fdr.setObjectName("checkBox_test_fdr")
        self.verticalLayout_2.addWidget(self.frameToolTest)
        self.frameToolTest_t = QtWidgets.QFrame(self.scrollAreaWidgetContentsTools)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameToolTest_t.sizePolicy().hasHeightForWidth())
        self.frameToolTest_t.setSizePolicy(sizePolicy)
        self.frameToolTest_t.setMinimumSize(QtCore.QSize(201, 91))
        self.frameToolTest_t.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameToolTest_t.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameToolTest_t.setObjectName("frameToolTest_t")
        self.label_test_t = QtWidgets.QLabel(self.frameToolTest_t)
        self.label_test_t.setGeometry(QtCore.QRect(10, 10, 101, 17))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setBold(True)
        font.setWeight(75)
        self.label_test_t.setFont(font)
        self.label_test_t.setObjectName("label_test_t")
        self.radioButton_test_t_variant_one = QtWidgets.QRadioButton(self.frameToolTest_t)
        self.radioButton_test_t_variant_one.setGeometry(QtCore.QRect(10, 30, 81, 17))
        self.radioButton_test_t_variant_one.setObjectName("radioButton_test_t_variant_one")
        self.buttonGroup_test_t_variant = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_test_t_variant.setObjectName("buttonGroup_test_t_variant")
        self.buttonGroup_test_t_variant.addButton(self.radioButton_test_t_variant_one)
        self.radioButton_test_t_variant_paired = QtWidgets.QRadioButton(self.frameToolTest_t)
        self.radioButton_test_t_variant_paired.setGeometry(QtCore.QRect(10, 70, 81, 17))
        self.radioButton_test_t_variant_paired.setObjectName("radioButton_test_t_variant_paired")
        self.buttonGroup_test_t_variant.addButton(self.radioButton_test_t_variant_paired)
        self.radioButton_test_t_variant_unpaired = QtWidgets.QRadioButton(self.frameToolTest_t)
        self.radioButton_test_t_variant_unpaired.setGeometry(QtCore.QRect(10, 50, 81, 17))
        self.radioButton_test_t_variant_unpaired.setObjectName("radioButton_test_t_variant_unpaired")
        self.buttonGroup_test_t_variant.addButton(self.radioButton_test_t_variant_unpaired)
        self.radioButton_test_t_tails_two = QtWidgets.QRadioButton(self.frameToolTest_t)
        self.radioButton_test_t_tails_two.setGeometry(QtCore.QRect(100, 30, 81, 17))
        self.radioButton_test_t_tails_two.setObjectName("radioButton_test_t_tails_two")
        self.buttonGroup_test_t_tails = QtWidgets.QButtonGroup(mainWindow)
        self.buttonGroup_test_t_tails.setObjectName("buttonGroup_test_t_tails")
        self.buttonGroup_test_t_tails.addButton(self.radioButton_test_t_tails_two)
        self.radioButton_test_t_tails_greater = QtWidgets.QRadioButton(self.frameToolTest_t)
        self.radioButton_test_t_tails_greater.setGeometry(QtCore.QRect(100, 50, 81, 17))
        self.radioButton_test_t_tails_greater.setObjectName("radioButton_test_t_tails_greater")
        self.buttonGroup_test_t_tails.addButton(self.radioButton_test_t_tails_greater)
        self.radioButton_test_t_tails_less = QtWidgets.QRadioButton(self.frameToolTest_t)
        self.radioButton_test_t_tails_less.setGeometry(QtCore.QRect(100, 70, 81, 17))
        self.radioButton_test_t_tails_less.setObjectName("radioButton_test_t_tails_less")
        self.buttonGroup_test_t_tails.addButton(self.radioButton_test_t_tails_less)
        self.verticalLayout_2.addWidget(self.frameToolTest_t)
        self.verticalLayoutGroups = QtWidgets.QVBoxLayout()
        self.verticalLayoutGroups.setObjectName("verticalLayoutGroups")
        self.verticalLayout_2.addLayout(self.verticalLayoutGroups)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.scrollAreaTools.setWidget(self.scrollAreaWidgetContentsTools)
        self.verticalLayout.addWidget(self.h_splitterMaster)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1077, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        self.menuGroups = QtWidgets.QMenu(self.menubar)
        self.menuGroups.setObjectName("menuGroups")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuExport = QtWidgets.QMenu(self.menubar)
        self.menuExport.setObjectName("menuExport")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuData.menuAction())
        self.menubar.addAction(self.menuGroups.menuAction())
        self.menubar.addAction(self.menuExport.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Brainwash"))
        self.pushButtonParse.setText(_translate("mainWindow", "Import"))
        self.checkBox_splitOddEven.setText(_translate("mainWindow", "Split odd/even sweeps"))
        self.label_splitTime.setText(_translate("mainWindow", "Split at (ms)"))
        self.label_gain.setText(_translate("mainWindow", "Apply gain"))
        self.checkBox_timepoints_per_stim.setText(_translate("mainWindow", "Timepoints per stim"))
        self.label_stims.setText(_translate("mainWindow", "Stims"))
        self.pushButton_stim_add.setText(_translate("mainWindow", "Add Stim"))
        self.label_mean_to.setText(_translate("mainWindow", "-"))
        self.label_mean_selected_range.setText(_translate("mainWindow", "Selection (ms)"))
        self.pushButton_stim_remove.setText(_translate("mainWindow", "Remove"))
        self.pushButton_hide_stim.setText(_translate("mainWindow", "-"))
        self.pushButton_sweeps_even.setText(_translate("mainWindow", "Even"))
        self.label_sweeps.setText(_translate("mainWindow", "Sweeps"))
        self.pushButton_sweeps_odd.setText(_translate("mainWindow", "Odd"))
        self.label_sweeps_dash.setText(_translate("mainWindow", "-"))
        self.label_sweeps_selection.setText(_translate("mainWindow", "Selected"))
        self.pushButton_hide_sweeps.setText(_translate("mainWindow", "-"))
        self.pushButton_add_to_set.setText(_translate("mainWindow", "Add to Test Set"))
        self.label_tag.setText(_translate("mainWindow", "Tag selection"))
        self.pushButton_hide_tag.setText(_translate("mainWindow", "-"))
        self.checkBox_is_group_sample.setText(_translate("mainWindow", "Use recording as sample"))
        self.label_bins.setText(_translate("mainWindow", "Bin size"))
        self.label_bin_zero_means_off.setText(_translate("mainWindow", "0 = no binning"))
        self.pushButton_hide_bin.setText(_translate("mainWindow", "-"))
        self.label_experiment_type.setText(_translate("mainWindow", "Experiment type"))
        self.radioButton_type_time.setText(_translate("mainWindow", "Time Course"))
        self.radioButton_type_train.setText(_translate("mainWindow", "Train"))
        self.radioButton_type_io.setText(_translate("mainWindow", "I-O"))
        self.pushButton_hide_type.setText(_translate("mainWindow", "-"))
        self.radioButton_type_sweep.setText(_translate("mainWindow", "Sweep Count"))
        self.radioButton_type_timestamp.setText(_translate("mainWindow", "Timestamp"))
        self.radioButton_type_pp.setText(_translate("mainWindow", "PP"))
        self.label_io_input.setText(_translate("mainWindow", "Input"))
        self.radioButton_io_vamp.setText(_translate("mainWindow", "volley amp."))
        self.radioButton_io_EPSPamp.setText(_translate("mainWindow", "ESPS amp."))
        self.radioButton_io_EPSPslope.setText(_translate("mainWindow", "EPSP slope"))
        self.radioButton_io_vslope.setText(_translate("mainWindow", "volley slope"))
        self.radioButton_io_stim.setText(_translate("mainWindow", "Stim"))
        self.label_io_output.setText(_translate("mainWindow", "Output"))
        self.checkBox_io_trendline.setText(_translate("mainWindow", "Trendline"))
        self.checkBox_io_force0.setText(_translate("mainWindow", "Force 0.0"))
        self.label_filter.setText(_translate("mainWindow", "Filter"))
        self.radioButton_filter_none.setText(_translate("mainWindow", "None"))
        self.radioButton_filter_savgol.setText(_translate("mainWindow", "SavGol"))
        self.pushButton_hide_filter.setText(_translate("mainWindow", "-"))
        self.label_filter_savgol.setText(_translate("mainWindow", "Savgol"))
        self.label_savgol_window.setText(_translate("mainWindow", "Window"))
        self.label_savgol_poly.setText(_translate("mainWindow", "Poly"))
        self.label_norm_on_sweep.setText(_translate("mainWindow", "Norm on sweep(s)"))
        self.checkBox_norm_EPSP.setText(_translate("mainWindow", "Relative"))
        self.label_relative_to.setText(_translate("mainWindow", "-"))
        self.label_y_axis.setText(_translate("mainWindow", "Y axis"))
        self.checkBox_output_ymin0.setText(_translate("mainWindow", "output Ymin 0"))
        self.pushButton_hide_y_axis.setText(_translate("mainWindow", "-"))
        self.checkBox_EPSP_slope.setText(_translate("mainWindow", "EPSP slope"))
        self.checkBox_volley_slope.setText(_translate("mainWindow", "volley slope"))
        self.checkBox_EPSP_amp.setText(_translate("mainWindow", "EPSP amp."))
        self.label_aspect.setText(_translate("mainWindow", "Aspect"))
        self.checkBox_volley_amp.setText(_translate("mainWindow", "volley amp."))
        self.checkBox_volley_slope_mean.setText(_translate("mainWindow", "mean"))
        self.checkBox_volley_amp_mean.setText(_translate("mainWindow", "mean"))
        self.pushButton_hide_aspect.setText(_translate("mainWindow", "-"))
        self.label_volley_slope_width.setText(_translate("mainWindow", "volley"))
        self.label_EPSP_slope_width.setText(_translate("mainWindow", "EPSP"))
        self.label_header_slope_width.setText(_translate("mainWindow", "Slope width (ms)"))
        self.pushButton_hide_slope_width.setText(_translate("mainWindow", "-"))
        self.label_volley_amp_halfwidth.setText(_translate("mainWindow", "volley"))
        self.label_EPSP_amp_halfwidth.setText(_translate("mainWindow", "EPSP"))
        self.label_header_amp_halfwidth.setText(_translate("mainWindow", "Amplitude width (± ms)"))
        self.pushButton_hide_amplitude_width.setText(_translate("mainWindow", "-"))
        self.label_test.setText(_translate("mainWindow", "Statistical test"))
        self.pushButton_hide_test.setText(_translate("mainWindow", "-"))
        self.radioButton_test_t.setText(_translate("mainWindow", "t-test"))
        self.radioButton_test_anova.setText(_translate("mainWindow", "ANOVA"))
        self.radioButton_test_wilcoxon.setText(_translate("mainWindow", "Wilcoxon"))
        self.radioButton_test_friedman.setText(_translate("mainWindow", "Friedman"))
        self.radioButton_test_cluster.setText(_translate("mainWindow", "Cluster perm."))
        self.checkBox_test_fdr.setText(_translate("mainWindow", "False Discovery Rate"))
        self.label_test_t.setText(_translate("mainWindow", "Student's t-test"))
        self.radioButton_test_t_variant_one.setText(_translate("mainWindow", "One-sample"))
        self.radioButton_test_t_variant_paired.setText(_translate("mainWindow", "Paired"))
        self.radioButton_test_t_variant_unpaired.setText(_translate("mainWindow", "Unpaired"))
        self.radioButton_test_t_tails_two.setText(_translate("mainWindow", "Two-sided"))
        self.radioButton_test_t_tails_greater.setText(_translate("mainWindow", "Greater"))
        self.radioButton_test_t_tails_less.setText(_translate("mainWindow", "Less"))
        self.menuFile.setTitle(_translate("mainWindow", "File"))
        self.menuData.setTitle(_translate("mainWindow", "Data"))
        self.menuGroups.setTitle(_translate("mainWindow", "Groups"))
        self.menuEdit.setTitle(_translate("mainWindow", "Edit"))
        self.menuView.setTitle(_translate("mainWindow", "View"))
        self.menuExport.setTitle(_translate("mainWindow", "Export"))
