"""Host Protocol contracts for UIsub mixins (documentation + optional typing)."""

from __future__ import annotations

from typing import Any, Protocol


class StatTestHost(Protocol):
    dd_groups: dict
    dd_testsets: dict
    dict_folders: dict
    uistate: Any
    uiplot: Any
    statusbar: Any
    progressBar: Any

    def get_group_testset_means(self, *args, **kwargs) -> Any: ...
    def _is_loading_active(self) -> bool: ...
    def graphRefresh(self, *, reeval_formal_test: bool = ...) -> None: ...
    def update_show(self) -> None: ...
    def mouseoverUpdate(self) -> None: ...
    def usage(self, msg: str) -> None: ...
    def V2mV(self, df) -> Any: ...
    def get_dfgroupmean(self, group_ID, *, level=None) -> Any: ...


class SelectionHost(Protocol):
    dd_groups: dict
    dict_folders: dict
    uistate: Any
    uiplot: Any

    def get_groupsOfRec(self, rec_ID) -> Any: ...
    def get_df_project(self) -> Any: ...
    def get_dft(self, *args, **kwargs) -> Any: ...
    def get_dffilter(self, p_row) -> Any: ...
    def update_filter_settings(self) -> None: ...
    def update_experiment_type_radio_buttons(self) -> None: ...
    def formatTableStimLayout(self) -> None: ...
    def setButtonParse(self) -> None: ...
    def graphUpdate(self) -> None: ...
    def zoomAuto(self) -> None: ...
    def graphRefresh(self, *, reeval_formal_test: bool = ...) -> None: ...
    def usage(self, msg: str) -> None: ...
    def _is_io_mode(self) -> bool: ...


class DataFrameHost(Protocol):
    dict_folders: dict
    uistate: Any
    config: Any
    uiplot: Any

    def get_dfmean(self, p_row) -> Any: ...
    def get_dffilter(self, p_row) -> Any: ...
    def V2mV(self, df) -> Any: ...