import json
import math
import os  # TODO: replace use by pathlib?
import sys
import tempfile
import traceback
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets, sip

# pandas 3.0 changed the default string dtype to Arrow-backed string[pyarrow],
# which rejects assignment of non-string values (int, float, etc.).
# The project DataFrame mixes strings, ints and floats in the same CSV-loaded
# DataFrame, so we opt back into the legacy object-dtype string behaviour.
pd.options.future.infer_string = False

# Matplotlib slowdown fix for frozen Windows builds: redirect config dir to temp.
# Must be set before matplotlib is imported so it sees the override on first init.
if getattr(sys, "frozen", False):
    os.environ.setdefault("MPLCONFIGDIR", os.path.join(tempfile.gettempdir(), "matplotlib"))

from matplotlib import use as matplotlib_use

matplotlib_use("Qt5Agg")


import logging
import pickle  # for saving and loading dicts
import re  # regular expressions
import socket  # getting computer name and localdomain for df_project['host'] (not reported in talkback)
import time  # counting time for functions

# used by talkback
import uuid  # generating unique talkback ID
from datetime import datetime  # used in project name defaults

import analysis_v3 as analysis
from brainwash_ui import plot_series

# brainwash files
import parse

# read and write
import toml  # for reading pyproject.toml
import ui_data_frames
import ui_designer  # Import the Designer-generated UI code
import ui_graph
import ui_groups
import ui_parse
import ui_plot
import ui_project
import ui_selection
import brainwash.ui_stat_test as ui_stat_test
import ui_state_classes
import ui_sweep_ops
import ui_table
import ui_widgets
import yaml  # used by talkback
from project_schema import df_projectTemplate

from . import statistics as stats  # our statistical testing layer (not the built-in stdlib module)

logger = logging.getLogger(__name__)
logger.debug("ui.py: os.getcwd(): %s", os.getcwd())

# NOTE: Large parts of UIsub have been extracted to mixins (see plan_ui_mixin_extraction.md):
# - Phase 0: widgets -> ui_widgets.py
# - Phase 1: table/selection -> ui_table.py + ui_selection.py (methods moved + cleaned; update_recs2plot/setViewToolVisible deduped)
# - Phase 2: graph/zoom -> ui_graph.py
# - Phase 3: parse -> ui_parse.py
# - Phase 4: stat tests/statusbar/n_unit -> ui_stat_test.py
# - Phase 5 (polish): connectUIstate/applyConfigStates/hierarchy/rename → ProjectMixin; stubs removed.
# Core UIsub now holds wiring, lifecycle, thin orchestration and non-extracted handlers. (ui.py ~2600 LOC)

import brainwash.export_data as export_data
import brainwash.ui_interactive as ui_interactive
import brainwash.ui_menus as ui_menus

####################################################################
# MAIN UI CLASS
####################################################################


# Composes Ui_MainWindow with all mixins.
class UIsub(
    ui_designer.Ui_mainWindow,
    ui_groups.GroupMixin,
    ui_sweep_ops.SweepOpsMixin,
    ui_project.ProjectMixin,
    ui_data_frames.DataFrameMixin,
    ui_menus.MenuMixin,
    export_data.ExportMixin,
    ui_interactive.InteractivePlotMixin,
    ui_table.TableMixin,
    ui_selection.SelectionMixin,
    ui_graph.GraphCoordinatorMixin,
    ui_parse.ParseMixin,
    ui_stat_test.StatTestMixin,
):
    def __init__(self, mainwindow):
        logger.debug("UIsub __init__ started")
        super(UIsub, self).__init__()
        logger.debug("super().__init__() done, calling setupUi...")
        self.setupUi(mainwindow)  # as generated by QtDesigner - do not touch!
        logger.debug("setupUi done")
        logger.debug("UIsub init")
        print(" - UIsub init, verbose mode")

        self.config = ui_widgets.Config()
        self.uistate = ui_state_classes.UIstate()
        self.uiplot = ui_plot.UIplot(self.uistate)

        # Custom UI initialization - non-QtDesigner-generated instructions
        self.pushButtonParse.setVisible(False)
        self.frameParseOptions.setVisible(False)
        self.progressBar.setVisible(False)
        self.progressBar.setValue(0)

        # Performance fixes for live splitter dragging on h_splitterMaster (esp. handle
        # between fields 0 and 1). These panels contain tables whose layouts/headers
        # were causing excessive work (and Wayland starvation) during continuous resizes.
        if hasattr(self, "verticalLayoutProj"):
            # The generated SetMinimumSize constraint causes extra layout iterations
            # when the splitter forces horizontal geometry changes on widgetProj.
            self.verticalLayoutProj.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        if hasattr(self, "h_splitterMaster"):
            # Disable live child resizing during drag. Children (tables) only resize
            # on handle release. This prevents a storm of resizeEvents, header size
            # calculations, and repaints on every mouse move while dragging.
            self.h_splitterMaster.setOpaqueResize(False)

        # Add a reliable stretchable centered label to the statusbar.
        # Using addWidget + our own QLabel gives us full control over alignment
        # (the QStatusBar's internal temporary message label from showMessage is
        # always left-aligned and hard to influence).
        self.statusbar_label = QtWidgets.QLabel()
        self.statusbar_label.setAlignment(QtCore.Qt.AlignCenter)
        self.statusbar_label.setText("")
        self.statusbar_label.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        self.statusbar.addWidget(self.statusbar_label, 1)

        # Statusbar is always present. Errors/warnings force red; successful stat test reports
        # and everything else use the default color so it is sensitive to darkmode toggles.
        try:

            def _initial_center():
                if hasattr(self, "statusbar_label") and self.statusbar_label:
                    self.statusbar_label.setAlignment(QtCore.Qt.AlignCenter)
                for lbl in self.statusbar.findChildren(QtWidgets.QLabel):
                    lbl.setAlignment(QtCore.Qt.AlignCenter)

            _initial_center()
            QtCore.QTimer.singleShot(0, _initial_center)
        except Exception:
            pass

        # Wire statusbar message restoration for test warnings after transient messages
        try:
            self.statusbar.messageChanged.connect(self._on_statusbar_message_cleared)
        except Exception:
            pass

        # Always force centered text for anything shown on the statusbar (warnings, loading, future messages, toasts)
        def _force_statusbar_text_centered(_text=None):
            try:

                def _do():
                    if hasattr(self, "statusbar_label") and self.statusbar_label:
                        self.statusbar_label.setAlignment(QtCore.Qt.AlignCenter)
                    for lbl in self.statusbar.findChildren(QtWidgets.QLabel):
                        lbl.setAlignment(QtCore.Qt.AlignCenter)

                _do()
                QtCore.QTimer.singleShot(0, _do)
            except Exception:
                pass

        try:
            self.statusbar.messageChanged.connect(_force_statusbar_text_centered)
        except Exception:
            pass

        logger.debug("Pre-bootstrap")
        self.bootstrap(mainwindow)  # set up general UI
        logger.debug("bootstrap done, calling loadProject...")
        self.loadProject()  # load project data
        logger.debug("loadProject done")

        # Debounced config saver: used by onSplitterMoved so continuous drag
        # does not spam disk I/O (which kills responsiveness and can crash Wayland).
        self._save_cfg_timer = QtCore.QTimer(self.mainwindow)
        self._save_cfg_timer.setSingleShot(True)
        self._save_cfg_timer.timeout.connect(self._debounced_save_cfg)

    def _cleanup_threads(self):
        # Stop and wait for all running threads
        for thread in getattr(self, "_threads", []):
            if isinstance(thread, QtCore.QThread) and thread.isRunning():
                thread.quit()
                thread.wait()
        self._threads = []

    def closeEvent(self, event):
        # Ensure all threads are stopped on window close
        self._cleanup_threads()
        # Persist UI state (incl. current splitter sizes) on close.
        # We deliberately do not save on every splitterMoved (see onSplitterMoved).
        self._save_cfg_now()

        super().closeEvent(event)

    def _save_cfg_now(self):
        """Immediate persist of cfg (used on close and after debounce)."""
        try:
            if hasattr(self, "dict_folders") and "project" in getattr(self, "dict_folders", {}):
                self.uistate.save_cfg(projectfolder=self.dict_folders["project"])
        except Exception:
            pass

    def _debounced_save_cfg(self):
        """Persist cfg after idle; called via timer from onSplitterMoved etc."""
        self._save_cfg_now()

    # Debugging tools

    def checkFocus(self):
        focused_widget = QtWidgets.QApplication.focusWidget()
        if focused_widget is not None:
            print(f"Focused Widget: {focused_widget.objectName()}")
        else:
            print("No widget has focus.")

    def find_widgets_with_top_left_coordinates(self, widget):
        print("trying child geometry")
        for child in widget.findChildren(QtWidgets.QWidget):
            # print(f"attribs: {dir(child.geometry())}")
            print(
                f"child.geometry(): {child.objectName()}, {child.geometry().topLeft()},  {child.mapTo(self.centralwidget, child.geometry().topLeft())}, {child.geometry().size()}"
            )

    ######################################################################
    #                     Selection changers                             #
    ######################################################################

    def update_filter_settings(self, df_p=None):
        """Helper for filter-settings population. Handles uniform/mixed selection
        logic for radio buttons (filter mode) and savgol lineEdits exactly as before.
        """
        if df_p is None:
            df_p = self.get_df_project()

        if len(self.uistate.plot.list_idx_select_recs) > 0:
            selected_df = df_p.loc[self.uistate.plot.list_idx_select_recs]

            # 1. Filter Mode (radio buttons)
            filters = selected_df["filter"].unique()
            # Treat NaN and 'none' as the same mode for uniformity checks
            filter_modes = set()
            for f in filters:
                if pd.isna(f) or f == "none" or f == "voltage":
                    filter_modes.add("voltage")
                else:
                    filter_modes.add(f)

            if len(filter_modes) == 1:
                f_mode = filter_modes.pop()
                if f_mode == "voltage":
                    self.uistate.project.settings["filter"] = "voltage"
                    self.radioButton_filter_none.setChecked(True)
                elif f_mode == "savgol":
                    self.uistate.project.settings["filter"] = "savgol"
                    self.radioButton_filter_savgol.setChecked(True)
            else:
                self.uistate.project.settings["filter"] = "voltage"
                self.buttonGroup_filter.setExclusive(False)
                self.radioButton_filter_none.setChecked(False)
                self.radioButton_filter_savgol.setChecked(False)
                self.buttonGroup_filter.setExclusive(True)

            # 2. Filter Params (lineEdits)
            windows = set()
            polys = set()
            for params_str in selected_df["filter_params"]:
                try:
                    params = json.loads(params_str) if pd.notna(params_str) and params_str else {}
                    windows.add(int(params.get("window_length", 9)))
                    polys.add(int(params.get("poly_order", 3)))
                except Exception:
                    windows.add(9)
                    polys.add(3)

            if len(windows) == 1:
                val = windows.pop()
                self.uistate.project.lineEdit["savgol_window"] = val
                self.lineEdit_savgol_window.setText(str(val))
            else:
                self.lineEdit_savgol_window.setText("")

            if len(polys) == 1:
                val = polys.pop()
                self.uistate.project.lineEdit["savgol_poly"] = val
                self.lineEdit_savgol_poly.setText(str(val))
            else:
                self.lineEdit_savgol_poly.setText("")
        else:
            self.buttonGroup_filter.setExclusive(False)
            self.radioButton_filter_none.setChecked(False)
            self.radioButton_filter_savgol.setChecked(False)
            self.buttonGroup_filter.setExclusive(True)
            self.lineEdit_savgol_window.setText("")
            self.lineEdit_savgol_poly.setText("")

    def stimSelectionChanged(self, *args):
        self.usage("stimSelectionChanged")
        if QtWidgets.QApplication.mouseButtons() == QtCore.Qt.RightButton:
            self.tableStim.clearSelection()

        if self.uistate.plot.mean_mouseover_stim_select is not None:  # clicked graph
            row = self.uistate.plot.mean_mouseover_stim_select - 1
            model_index = self.tableStimModel.index(row, 0)

            modifiers = QtWidgets.QApplication.keyboardModifiers()
            if modifiers & QtCore.Qt.ControlModifier:
                flag = QtCore.QItemSelectionModel.Toggle | QtCore.QItemSelectionModel.Rows
            else:
                flag = QtCore.QItemSelectionModel.ClearAndSelect | QtCore.QItemSelectionModel.Rows

            self.uistate.plot.mean_mouseover_stim_select = None

            # Safely disconnect if connected to prevent a recursive loop
            try:
                self.tableStim.selectionModel().selectionChanged.disconnect(self.stimSelectionChanged)
            except TypeError:
                pass
            self.tableStim.selectionModel().select(model_index, flag)
            self.tableStim.selectionModel().selectionChanged.connect(self.stimSelectionChanged)

        selected_indexes = self.tableStim.selectionModel().selectedRows()

        # build the list self.uistate.plot.list_idx_select_stims with indices
        self.uistate.plot.list_idx_select_stims = [index.row() for index in selected_indexes]

        # update single-recording reference dataframe if applicable
        if len(self.uistate.plot.list_idx_select_recs) == 1:
            prow = self.get_prow()
            if prow is not None:
                self.uistate.plot.df_rec_select_time = self.get_dft(row=prow)
        else:
            self.uistate.plot.df_rec_select_time = None

        self.update_stim_buttons()
        self.update_show()
        self.zoomAuto()
        self.update_amp_lineEdits()
        self.update_slope_lineEdits()
        self.update_stim_buttons()
        self.mouseoverUpdate()

    def deleteFolder(self, dir_path):
        if os.path.exists(dir_path):
            for filename in os.listdir(dir_path):
                file_path = os.path.join(dir_path, filename)
                if os.path.isfile(file_path) or os.path.islink(file_path):
                    os.unlink(file_path)  # remove file or symlink
                elif os.path.isdir(file_path):
                    self.deleteFolder(file_path)  # recursively remove a subdirectory
            os.rmdir(dir_path)  # remove the directory itself

    def uiFreeze(self):  # Disable selection changes and checkboxes
        if self.uistate.plot.frozen:
            return
        self.uistate.plot.frozen = True
        self.tableProj.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableStim.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.connectUIstate(disconnect=True)
        for key, _ in self.uistate.project.checkBox.items():
            if hasattr(self, f"checkBox_{key}"):
                checkBox = getattr(self, f"checkBox_{key}")
                checkBox.setEnabled(False)
        for radio_name in (
            list(self._RADIO_TO_TYPE)
            + list(self._RADIO_TO_TEST)
            + list(self._RADIO_TO_TEST_T_VARIANT)
            + list(self._RADIO_TO_TEST_T_TAILS)
            + list(self._RADIO_TO_TEST_WILCOX_VARIANT)
            + list(self._RADIO_TO_TEST_WILCOX_TAILS)
            + list(self._RADIO_TO_TEST_N)  # v0.16_n_stats
        ):
            if hasattr(self, radio_name):
                getattr(self, radio_name).setEnabled(False)  # ET/TT radios always enabled per plan (warnings via statusbar)

    def uiThaw(self):  # Enable selection changes and checkboxes
        if not self.uistate.plot.frozen:
            return
        self.tableProj.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.tableStim.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.connectUIstate()
        for key, _ in self.uistate.project.checkBox.items():
            if hasattr(self, f"checkBox_{key}"):
                checkBox = getattr(self, f"checkBox_{key}")
                checkBox.setEnabled(True)
        for radio_name in (
            list(self._RADIO_TO_TYPE)
            + list(self._RADIO_TO_TEST)
            + list(self._RADIO_TO_TEST_T_VARIANT)
            + list(self._RADIO_TO_TEST_T_TAILS)
            + list(self._RADIO_TO_TEST_WILCOX_VARIANT)
            + list(self._RADIO_TO_TEST_WILCOX_TAILS)
            + list(self._RADIO_TO_TEST_N)  # v0.16_n_stats
        ):
            if hasattr(self, radio_name):
                getattr(self, radio_name).setEnabled(True)  # ET/TT radios always enabled per plan (warnings via statusbar)
        # Radio button enabled-state is recording-dependent; a full refresh
        # via tableProjSelectionChanged (called after uiThaw) will set them
        # correctly.  Here we just re-enable sweep (always valid) so the
        # group is not left fully disabled.
        if hasattr(self, "radioButton_type_sweep"):
            self.radioButton_type_sweep.setEnabled(True)
        self.uistate.plot.frozen = False

    def toggleHeatmap(self):
        self.uistate.plot.showHeatmap = not self.uistate.plot.showHeatmap
        print(f"Heatmap is {self.uistate.plot.showHeatmap}")
        if not self.uistate.plot.showHeatmap:
            self.uiplot.heatunmap()
            self.set_statusbar(None, None)  # pure display refresh (no test recompute)
            return
        t0 = time.time()
        d_group_ndf = {}
        list_l = []
        n_sig = 0
        for key, sub_dict in self.dd_groups.items():
            if sub_dict["show"]:
                n = len(sub_dict["rec_IDs"])
                level = self.uistate.stat_test.buttonGroup_test_n
                df = self.get_dfgroupmean(key, level=level)
                list_l.append(len(df))
                d_group_ndf[key] = [n, df]
        if len(d_group_ndf) == 2:
            if list_l[0] == list_l[1]:
                for key, ndf in d_group_ndf.items():
                    n = ndf[0]
                    df = ndf[1]
                    l = len(df)
                    list_l.append(l)
                    print(f"{key} - N: {n} - {l} sweeps")
                # perform test
                norm = self.uistate.project.checkBox["norm_EPSP"]
                amp = self.uistate.project.checkBox["EPSP_amp"]
                slope = self.uistate.project.checkBox["EPSP_slope"]
                df_ttest = analysis.ttest_df(d_group_ndf, norm=norm, amp=amp, slope=slope)
                if not df_ttest.empty:
                    self.uiplot.heatmap(df_ttest)
                    pcols = [c for c in df_ttest.columns if c.startswith("p_")]
                    if pcols:
                        try:
                            n_sig = int((df_ttest[pcols] < 0.05).any(axis=1).sum())
                        except Exception:
                            n_sig = 0
                print(df_ttest)
            else:
                print("t-test requires number of sweeps to match")
        else:
            print("t-test currently only available between exactly 2 shown groups")
        print(f"Heatmap: {round((time.time() - t0) * 1000)} ms")
        if n_sig == 1:
            msg = "Heatmap: 1 data point is significantly different"
        else:
            msg = f"Heatmap: {n_sig} data points are significantly different"
        self._set_statusbar_appearance(text=msg)

    def turn_heatmap_off(self):
        """Turn off heatmap (if on), remove any dots, sync menu, and restore normal statusbar."""
        if self.uistate.plot.showHeatmap:
            self.uistate.plot.showHeatmap = False
            try:
                self.uiplot.heatunmap()
            except Exception:
                pass
            try:
                if hasattr(self, "actionHeatmap") and self.actionHeatmap is not None:
                    self.actionHeatmap.setChecked(False)
            except Exception:
                pass
            try:
                self.set_statusbar(None, None)  # pure display refresh after heatmap disable
            except Exception:
                pass

    def talkback(self):
        prow = self.get_prow()
        if prow is None:
            logger.debug("talkback: prow is None, returning early")
            return
        trow = self.get_trow()
        if trow is None:
            logger.debug("talkback: trow is None, returning early")
            return
        dfmean = self.get_dfmean(prow)
        t_stim = trow["t_stim"]
        t_start = t_stim - 0.002
        t_end = t_stim + 0.018
        dfevent = dfmean[(dfmean["time"] >= t_start) & (dfmean["time"] < t_end)]
        dfevent = dfevent[["time", "voltage"]]
        path_talkback_df = Path(f"{self.projects_folder}/talkback/talkback_slice_{prow['ID']}_stim.csv")
        if not path_talkback_df.parent.exists():
            path_talkback_df.parent.mkdir(parents=True, exist_ok=True)
        dfevent.to_csv(path_talkback_df, index=False)
        # save the event data as a dict
        keys = [
            #            't_EPSP_amp', 't_EPSP_amp_method', 't_EPSP_amp_params',
            "t_EPSP_slope_start",
            "t_EPSP_slope_end",  #'t_EPSP_slope_method', 't_EPSP_slope_params',
            #'t_volley_amp', 't_volley_amp_method', 't_volley_amp_params',
            "t_volley_slope_start",
            "t_volley_slope_end",  # 't_volley_slope_method', 't_volley_slope_params'
        ]
        dict_event = {key: trow[key] for key in keys}
        print(f"talkback dict_event: {dict_event}")
        # store dict_event as .csv named after recording_name
        path_talkback = Path(f"{self.projects_folder}/talkback/talkback_meta_{prow['ID']}_stim.csv")
        with open(path_talkback, "w") as f:
            json.dump(dict_event, f)

    def darkmode(self):
        if self.uistate.darkmode:
            self.mainwindow.setStyleSheet("background-color: #2A2A2A; color: #fff;")
            self.progressBar.setStyleSheet(
                "QProgressBar { text-align: center; color: #fff; font-weight: bold; background-color: #333; border: 1px solid #555; border-radius: 3px; }"
                "QProgressBar::chunk { background-color: #1a6ea8; border-radius: 3px; }"
            )

            table_style = """
                QTableView::item:selected {
                    background-color: #555;
                    color: #FFF;
                }
                QHeaderView::section {
                    background-color: #333;
                    color: #FFF;
                }
                QTableCornerButton::section {
                    background-color: #333;
                    color: #FFF;
                }
            """
            self.tableProj.setStyleSheet(table_style)
            self.tableStim.setStyleSheet(table_style)

            # Explicit statusbar dark theme (matches mainwindow; avoids default grey)
            self.statusbar.setStyleSheet("""
                QStatusBar {
                    background-color: #2A2A2A;
                    color: #ddd;
                }
                QStatusBar QLabel {
                    background-color: transparent;
                    color: #ddd;
                }
            """)

        else:
            self.mainwindow.setStyleSheet("")
            self.tableProj.setStyleSheet("")
            self.tableStim.setStyleSheet("")

            self.progressBar.setStyleSheet(
                "QProgressBar { text-align: center; color: #000; font-weight: bold; background-color: #e0e0e0; border: 1px solid #bbb; border-radius: 3px; }"
                "QProgressBar::chunk { background-color: #4caf50; border-radius: 3px; }"
            )

            # Reset statusbar to Qt default (light theme, transparent label)
            self.statusbar.setStyleSheet("""
                QStatusBar {
                    background-color: transparent;
                }
                QStatusBar QLabel {
                    background-color: transparent;
                }
            """)

        self.uiplot.styleUpdate()
        self.graphRefresh()

        # Re-apply statusbar state (after darkmode stylesheet reset). Warnings stay red; reports use theme default.
        try:
            if not self._is_loading_active():
                self.set_statusbar(None, None)  # pure display refresh (no test recompute)
        except Exception:
            pass

    # update_recs2plot moved to TableMixin (ui_table.py)

    # --- X-axis radio button mapping ---
    _RADIO_TO_MODE = {
        "radioButton_xscale_sweep": "sweep",
        "radioButton_xscale_time": "time",
        "radioButton_xscale_stim": "stim",
        "radioButton_xscale_timestamp": "timestamp",
    }
    _MODE_TO_RADIO = {v: k for k, v in _RADIO_TO_MODE.items()}

    def filter_mode_changed(self, button):
        """Handler for buttonGroup_filter.buttonClicked signal."""
        mode_str = button.objectName().replace("radioButton_filter_", "")
        mode = mode_str if mode_str != "none" else "voltage"

        self.usage(f"filter_mode_changed → {mode}")
        self.uistate.project.settings["filter"] = mode
        print(f"filter_mode_changed: self.uistate.project.settings['filter'] set to {mode}")
        self.frameToolFilter_sub_Savgol.setVisible(mode == "savgol")

        df_p = self.get_df_project()
        if "filter" in df_p.columns and df_p["filter"].dtype != object:
            df_p["filter"] = df_p["filter"].astype(object)
        selected_idx = self.uistate.plot.list_idx_select_recs
        if len(selected_idx) > 0:
            for idx in selected_idx:
                df_p.at[idx, "filter"] = mode
            self.set_df_project(df_p)
            self.tableUpdate(restore_selection=True)
            self.recalculate(selection=selected_idx)
            self.update_show()

    def editSavgolParams(self, lineEdit):
        try:
            val = int(lineEdit.text())
        except ValueError:
            return

        key = lineEdit.objectName().replace("lineEdit_", "")

        self.usage(f"editSavgolParams → {key}: {val}")
        self.uistate.project.lineEdit[key] = val
        print(f"editSavgolParams: self.uistate.project.lineEdit['{key}'] set to {val}")

        df_p = self.get_df_project()
        if "filter_params" in df_p.columns and df_p["filter_params"].dtype != object:
            df_p["filter_params"] = df_p["filter_params"].astype(object)
        selected_idx = self.uistate.plot.list_idx_select_recs

        if len(selected_idx) > 0:
            for idx in selected_idx:
                try:
                    params_str = df_p.at[idx, "filter_params"]
                    params = json.loads(params_str) if pd.notna(params_str) and params_str else {}
                except Exception:
                    params = {}

                if key == "savgol_window":
                    params["window_length"] = val
                elif key == "savgol_poly":
                    params["poly_order"] = val

                df_p.at[idx, "filter_params"] = json.dumps(params)

            self.set_df_project(df_p)
            self.tableUpdate(restore_selection=True)
            self.recalculate(selection=selected_idx)
            self.update_show()

    _RADIO_TO_TYPE = {
        "radioButton_type_time": "time",
        "radioButton_type_train": "train",
        "radioButton_type_io": "io",
        "radioButton_type_pp": "PP",
        "radioButton_type_sweep": "sweep",
        "radioButton_type_timestamp": "timestamp",
    }
    _TYPE_TO_RADIO = {v: k for k, v in _RADIO_TO_TYPE.items()}

    _RADIO_TO_IO_I = {
        "radioButton_io_vamp": "vamp",
        "radioButton_io_vslope": "vslope",
        "radioButton_io_stim": "stim",
    }
    _IO_I_TO_RADIO = {v: k for k, v in _RADIO_TO_IO_I.items()}

    _RADIO_TO_IO_O = {
        "radioButton_io_EPSPamp": "EPSPamp",
        "radioButton_io_EPSPslope": "EPSPslope",
    }
    _IO_O_TO_RADIO = {v: k for k, v in _RADIO_TO_IO_O.items()}

    _RADIO_TO_TEST = {
        "radioButton_test_none": "None",
        "radioButton_test_t": "t-test",
        "radioButton_test_anova": "ANOVA",
        "radioButton_test_ancova": "ANCOVA",  # mapped per updated ui_designer.py (radioButton_test_ancova)
        "radioButton_test_wilcoxon": "Wilcoxon",
        "radioButton_test_friedman": "Friedman",
        "radioButton_test_cluster": "Cluster perm.",
    }
    _TEST_TO_RADIO = {v: k for k, v in _RADIO_TO_TEST.items()}

    _RADIO_TO_TEST_T_VARIANT = {
        "radioButton_test_t_variant_one": "one-sample",
        "radioButton_test_t_variant_paired": "paired",
        "radioButton_test_t_variant_unpaired": "unpaired",
    }
    _TEST_T_VARIANT_TO_RADIO = {v: k for k, v in _RADIO_TO_TEST_T_VARIANT.items()}

    _RADIO_TO_TEST_T_TAILS = {
        "radioButton_test_t_tails_two": "two-sided",
        "radioButton_test_t_tails_greater": "greater",
        "radioButton_test_t_tails_less": "less",
    }
    _TEST_T_TAILS_TO_RADIO = {v: k for k, v in _RADIO_TO_TEST_T_TAILS.items()}

    _RADIO_TO_TEST_WILCOX_VARIANT = {
        "radioButton_wilcoxon_variant_paired": "paired",
        "radioButton_wilcoxon_variant_one": "one-sample",
    }
    _TEST_WILCOX_VARIANT_TO_RADIO = {v: k for k, v in _RADIO_TO_TEST_WILCOX_VARIANT.items()}

    _RADIO_TO_TEST_WILCOX_TAILS = {
        "radioButton_wilcoxon_tails_two": "two-sided",
        "radioButton_wilcoxon_tails_greater": "greater",
        "radioButton_wilcoxon_tails_less": "less",
    }
    _TEST_WILCOX_TAILS_TO_RADIO = {v: k for k, v in _RADIO_TO_TEST_WILCOX_TAILS.items()}

    # v0.16_n_stats: n_unit radios (subject default per statistical_protocol.md + clarifications)
    # Follows exact existing pattern for test_* groups (no overhaul).
    _RADIO_TO_TEST_N = {
        "radioButton_test_n_subject": "subject",
        "radioButton_test_n_slice": "slice",
        "radioButton_test_n_rec": "recording",
    }
    _TEST_N_TO_RADIO = {v: k for k, v in _RADIO_TO_TEST_N.items()}

    def io_input_changed(self, button):
        """Handler for buttonGroup_io_i.buttonClicked signal."""
        io_input = self._RADIO_TO_IO_I.get(button.objectName())
        if io_input is None or io_input == self.uistate.experiment.io_input:
            return
        self.usage(f"io_input_changed → {io_input}")
        self.uistate.experiment.io_input = io_input
        self.uistate.save_cfg(projectfolder=self.dict_folders["project"])
        self.exorcise()
        self.triggerRefresh()

    def io_output_changed(self, button):
        """Handler for buttonGroup_io_o.buttonClicked signal."""
        io_output = self._RADIO_TO_IO_O.get(button.objectName())
        if io_output is None or io_output == self.uistate.experiment.io_output:
            return
        self.usage(f"io_output_changed → {io_output}")
        self.uistate.experiment.io_output = io_output
        self.uistate.save_cfg(projectfolder=self.dict_folders["project"])
        self.exorcise()
        self.triggerRefresh()

    def experiment_type_changed(self, button):
        """Handler for buttonGroup_type.buttonClicked signal."""
        exp_type = self._RADIO_TO_TYPE.get(button.objectName())
        old_type = self.uistate.experiment.experiment_type
        if exp_type is None or exp_type == old_type:
            return
        self.usage(f"experiment_type_changed → {exp_type}")
        self.uistate.experiment.experiment_type = exp_type
        if hasattr(self, "frameToolType_sub_io"):
            self.frameToolType_sub_io.setVisible(exp_type == "io")
        if exp_type == "io":
            # No test_type sentinel (experiment_type="io" is first-class per AGENTS.md and plan).
            # Test frame visibility now controlled ONLY by menu or pushButton_hide_test (setViewToolVisible / viewTools).
            # No auto-hide or gray menu.
            if hasattr(self, "frameToolTestOptions"):
                getattr(self, "frameToolTestOptions").setVisible(True)  # n_unit relevant for regression granularity
        self.uistate.save_cfg(projectfolder=self.dict_folders["project"])
        # Clear stale results; update_test is the single entry point (re-eval + statusbar via _get...).
        self.uistate.stat_test.formal_test_results = None
        # Do not unconditionally reset statusbar_state here; let _get_statusbar_for_current_state
        # (called from update_test) set "warning" for invalid t-test state (e.g. no test sets).
        # This matches launch-time behavior where warning color is set correctly.
        self.update_test()
        if exp_type == "io":
            self.exorcise()
            self.triggerRefresh()
            self.zoomAuto()
            self.graphRefresh()
            # graphRefresh (default) ends with update_test() for test+statusbar
        elif old_type == "io":
            # Re-show via viewTools/menu (no _should_show_stat_test_frame dependency for test frame).
            self.update_show()
            self.zoomAuto()
            self.graphRefresh()
        else:
            self.update_show()
            self.zoomAuto()
            self.graphRefresh()

    def viewSettingsChanged(self, key, state):
        self.usage(f"viewSettingsChanged {key}, {state == 2}")
        if key in self.uistate.project.checkBox:
            self.uistate.project.checkBox[key] = state == 2
            if key == "splitOddEven":
                self.checkBox_splitOddEven_changed(state)
            elif key == "timepoints_per_stim":
                self.checkBox_timepoints_per_stim_changed(state)
            elif key == "io_trendline":
                print(f"Checkbox io_trendline clicked, state: {state == 2}")
            elif key == "io_force0":
                print(f"Checkbox io_force0 clicked, state: {state == 2}")
                if self._is_io_mode():
                    self.exorcise()
                    self.triggerRefresh()
            elif key == "is_group_sample":
                self.checkBox_is_group_sample_changed(state)
            elif key == "label_test_t_one_sample_value":
                pass
        elif key == "test_fdr":
            self.uistate.stat_test.test_fdr = state == 2
            self.update_test()
        elif key == "test_sw":
            self.uistate.stat_test.test_sw = state == 2
            self.update_test()
        elif key == "test_levene":
            self.uistate.stat_test.test_levene = state == 2
            self.update_test()
        # print(f"viewSettingsChanged: {key} = {state == 2}")
        self.update_show()
        if key in ["output_ymin0", "norm_EPSP"]:
            self.zoomAuto()
        elif self.uistate.experiment.experiment_type == "PP" and key in ["EPSP_amp", "volley_amp", "EPSP_slope", "volley_slope"]:
            self.zoomAuto()
        # norm/amp/slope (visible aspects) affect heatmap and statistical test inputs;
        # clear stale heatmap dots and formal test markers when they change.
        aspect_keys = ["norm_EPSP", "EPSP_amp", "EPSP_slope", "volley_amp", "volley_slope", "volley_amp_mean", "volley_slope_mean"]
        if key in aspect_keys or key in ("test_fdr", "test_sw", "test_levene"):
            self.clear_formal_test_results()
        if key in aspect_keys:
            self.turn_heatmap_off()
        self.update_anova_label()  # sync if test sets changed indirectly
        self.graphRefresh()
        self.uistate.save_cfg(projectfolder=self.dict_folders["project"])

    def groupControlsRefresh(self):
        self.group_controls_remove()
        for group_ID in self.dd_groups.keys():
            self.group_controls_add(group_ID)

    def testsetControlsRefresh(self):
        self.testset_controls_remove()
        for set_ID in getattr(self, "dd_testsets", {}).keys():
            self.testset_controls_add(set_ID)
        self.update_anova_label()  # sync label after test set UI refresh

    def usage(self, ui_component):  # Talkback function
        logger.debug("usage: %s", ui_component)
        print(f"usage: {ui_component}")
        if not self.config.talkback:
            return
        if ui_component not in self.dict_usage.keys():
            self.dict_usage[ui_component] = 0
        self.dict_usage[ui_component] += 1
        if self.config.talkback and ui_component in self.dict_usage:
            # Do not clobber an active test warning (red statusbar)
            if self.uistate.stat_test.statusbar_state != "warning":
                # Show as centered text using the current default (theme/darkmode) color
                self._set_statusbar_appearance(text=f"Used {ui_component} {self.dict_usage[ui_component]} times", bold=False)
        self.write_usage()

    def write_usage(self):
        path_usage = Path(f"{self.projects_folder}/talkback/usage.yaml")
        if not path_usage.parent.exists():
            path_usage.parent.mkdir(parents=True, exist_ok=True)
        # make sure 'WARNING' and 'alias' are printed first
        top_keys = ["WARNING", "alias"]
        dict_bottom = self.dict_usage.copy()
        top_data = {key: dict_bottom.pop(key, None) for key in top_keys}
        with path_usage.open("w") as file:
            yaml.safe_dump(top_data, file, default_flow_style=False)
            yaml.safe_dump(dict_bottom, file, default_flow_style=False)

    def resetCacheDicts(self):
        self.dict_datas = {}  # all raw data
        self.dict_filters = {}  # all processed data, based on raw data
        self.dict_bins = {}  # all binned data, based on filters
        self.dict_means = {}  # all means
        self.dict_ts = {}  # all timepoints
        self.dict_outputs = {}  # all outputs, x per sweep
        self.dict_group_means = {}  # means of all group outputs (level-aware keys (gid, level))
        self.dict_global_units = {}  # global subject/slice unit dfs (keyed by (level, subject, slice?))
        self.dd_testsets = {}  # test/sweep sets for group comparisons
        self.dd_group_samples = {}  # group sample means (phase 3.3: group_ID -> {test_ID: df})
        self.dict_diffs = {}  # all diffs (for paired stim)
        if hasattr(self, "uistate") and hasattr(self.uistate.plot, "testset_spans"):
            self.uistate.plot.testset_spans = {}  # clear testset spans on cache reset (Phase 2)

    # uisub init refactoring (bootstrap and loadProject live in ProjectMixin)

    def setupTalkback(self):
        path_usage = Path(f"{self.projects_folder}/talkback/usage.yaml")
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        if path_usage.exists():
            with path_usage.open("r") as file:
                self.dict_usage = yaml.safe_load(file)
            self.dict_usage[f"last_used_{self.config.version}"] = now
        else:
            os_name = sys.platform
            self.dict_usage = {
                "WARNING": "Do NOT set your alias to anything that can be used to identify you!",
                "alias": "",
                "ID": str(uuid.uuid4()),
                "os": os_name,
                "ID_created": now,
                f"last_used_{self.config.version}": now,
            }
        self.write_usage()

    # setupFolders / build_dict_folders / setupToolBar / setSplitterSizes / connectUIstate /
    # applyConfigStates / hierarchy / renameRecording in ProjectMixin (ui_project.py)

    def groupCheckboxChanged(self, state, group_ID):
        logger.debug("groupCheckboxChanged: %s = %s", group_ID, state)
        print(f"groupCheckboxChanged: {str(group_ID)} = {state}")
        self.dd_groups[group_ID]["show"] = state == 2
        self.group_save_dd()
        self.refresh_samples()
        self.update_stim_buttons()
        self.update_show()
        self.mouseoverUpdate()
        self.update_test()

    def triggerGroupRename(self, group_ID):
        self.usage("triggerGroupRename")
        RenameDialog = ui_widgets.InputDialogPopup()
        new_group_name = RenameDialog.showInputDialog(title="Rename group", query="")
        self.group_rename(group_ID, new_group_name)

    def testsetCheckboxChanged(self, state, set_ID):
        self.usage("testsetCheckboxChanged")
        logger.debug("testsetCheckboxChanged: %s = %s", set_ID, state)
        print(f"testsetCheckboxChanged: {str(set_ID)} = {state}")
        self.dd_testsets[set_ID]["show"] = bool(state == 2)
        self.testset_save_dd()
        if hasattr(self, "dd_group_samples"):
            self.dd_group_samples = {}
        self.refresh_samples()
        self.uiplot.clear_sample_artists(draw=False)
        # Changing shown test sets requires fresh statistical markers (not stale cached results)
        self.clear_formal_test_results()
        self.update_anova_label()  # update ANOVA label if visible
        self.graphRefresh()
        # graphRefresh (default) ends with update_test() which re-evaluates the test and statusbar

    def triggerTestSetRename(self, set_ID):
        self.usage("triggerTestSetRename")
        RenameDialog = ui_widgets.InputDialogPopup()
        new_set_name = RenameDialog.showInputDialog(title="Rename test set", query="")
        if new_set_name:
            self.testset_rename(set_ID, new_set_name)

    def triggerStimAdd(self):
        self.usage("triggerStimAdd")
        if not self.uistate.plot.list_idx_select_recs:
            print("triggerStimAdd: No files selected.")
            return

        t_start = self.uistate.plot.x_select["mean_start"]
        if t_start is None:
            print("triggerStimAdd: No selection in axm.")
            return

        df_p = self.get_df_project()

        for index in self.uistate.plot.list_idx_select_recs:
            p_row = df_p.loc[index]
            rec_name = p_row["recording_name"]
            rec_ID = p_row["ID"]

            df_t = self.get_dft(p_row)

            new_row = self.uistate.project.default_dict_t.copy()
            new_row["t_stim"] = t_start

            # Make sure it's constructed securely as a 1D Series converting to DataFrame
            # so Pandas won't treat shape as (1,) arrays internally
            df_new = pd.DataFrame([new_row])

            # Type cast to safely concat without dimensionality glitches
            if "t_stim" in df_t.columns and df_new["t_stim"].dtype != df_t["t_stim"].dtype:
                df_new["t_stim"] = df_new["t_stim"].astype(df_t["t_stim"].dtype)

            df_t = pd.concat([df_t, df_new], ignore_index=True)
            df_t = df_t.sort_values("t_stim").reset_index(drop=True)
            df_t["stim"] = range(1, len(df_t) + 1)

            self.set_dft(rec_name, df_t)
            df_p.loc[p_row["ID"] == df_p["ID"], "stims"] = len(df_t)

            self.dict_outputs.pop(rec_name, None)
            path_output = self.dict_folders["cache"] / f"{rec_name}_output.parquet"
            if path_output.exists():
                path_output.unlink()

            dfoutput = self.get_dfoutput(p_row)

            self.uiplot.unPlot(rec_ID)
            dfmean = self.get_dfmean(p_row)
            self.uiplot.addRow(p_row, df_t, dfmean, self.V2mV(dfoutput))

        self.set_df_project(df_p)

        self.uistate.plot.x_select["mean_start"] = None
        self.uistate.plot.x_select["mean_end"] = None
        self.lineEdit_mean_selection_start.setText("")
        self.lineEdit_mean_selection_end.setText("")

        self.uistate.plot.list_idx_select_stims = [0]
        p_row = df_p.loc[self.uistate.plot.list_idx_select_recs[0]]
        df_t = self.get_dft(p_row)
        self.tableStimModel.setData(df_t)
        self.formatTableStimLayout(df_t)
        if len(df_t) > 0:
            self.tableStim.selectRow(0)
        else:
            self.stimSelectionChanged()

        self.graphRefresh()
        self.update_show(reset=True)
        self.zoomAuto()
        self.update_amp_lineEdits()
        self.update_slope_lineEdits()
        self.update_stim_buttons()
        self.mouseoverUpdate()

    def triggerStimRemove(self):
        self.usage("triggerStimRemove")
        if not self.uistate.plot.list_idx_select_recs:
            print("triggerStimRemove: No files selected.")
            return
        if not self.uistate.plot.list_idx_select_stims:
            print("triggerStimRemove: No stims selected to remove.")
            return

        df_p = self.get_df_project()

        for index in self.uistate.plot.list_idx_select_recs:
            p_row = df_p.loc[index]
            rec_name = p_row["recording_name"]
            rec_ID = p_row["ID"]

            df_t = self.get_dft(p_row)
            dfoutput = self.get_dfoutput(p_row)

            stims_to_remove = sorted(self.uistate.plot.list_idx_select_stims, reverse=True)
            for idx_stim in stims_to_remove:
                if idx_stim < len(df_t):
                    stim_id = df_t.iloc[idx_stim]["stim"]
                    # Drop from dft
                    df_t = df_t.drop(idx_stim).reset_index(drop=True)
                    # Drop from dfoutput
                    dfoutput = dfoutput[dfoutput["stim"] != stim_id].reset_index(drop=True)

            # Re-index remaining stims starting from 1
            if not df_t.empty:
                df_t["stim"] = range(1, len(df_t) + 1)
                # Remap the output stim IDs as well
                stim_mapping = {old: new for new, old in enumerate(dfoutput["stim"].unique(), 1)}
                dfoutput["stim"] = dfoutput["stim"].map(stim_mapping)

            # Save changes
            self.set_dft(rec_name, df_t)
            df_p.loc[p_row["ID"] == df_p["ID"], "stims"] = len(df_t)
            self.persistOutput(rec_name, dfoutput, p_row=p_row)
            dfoutput = self.get_dfoutput(p_row)

            # Unplot and replot to update visuals
            self.uiplot.unPlot(rec_ID)
            dfmean = self.get_dfmean(p_row)
            self.uiplot.addRow(p_row, df_t, dfmean, self.V2mV(dfoutput))

        self.set_df_project(df_p)

        # Reset selection to first stim (or empty if none left)
        self.uistate.plot.list_idx_select_stims = [0] if len(df_t) > 0 else []
        p_row = df_p.loc[self.uistate.plot.list_idx_select_recs[0]]
        df_t = self.get_dft(p_row)
        self.tableStimModel.setData(df_t)
        self.formatTableStimLayout(df_t)
        if len(df_t) > 0:
            self.tableStim.selectRow(0)
        else:
            # Let stimSelectionChanged run its cleanup manually since we can't trigger it via selectRow
            self.stimSelectionChanged()

        self.graphRefresh()
        self.update_show(reset=True)
        self.zoomAuto()
        self.update_amp_lineEdits()
        self.update_slope_lineEdits()
        self.update_stim_buttons()
        self.mouseoverUpdate()

    def trigger_set_sweeps_even(self):
        self.usage("trigger_set_sweeps_even")
        self.sweepsSelect(even=True)

    def trigger_set_sweeps_odd(self):
        self.usage("trigger_set_sweeps_odd")
        self.sweepsSelect(even=False)

    def trigger_set_norm_range_all(self):
        self.usage("trigger_set_norm_range_all")
        self.recalculate()

    def trigger_set_bin_size_all(self):
        self.usage("trigger_set_bin_size_all")
        text = self.lineEdit_bin_size.text().strip()
        if not text:
            return
        try:
            num = int(text.replace(",", "."))
        except ValueError:
            return
        derived = float("nan") if num <= 1 else num
        df_p = self.get_df_project()
        for idx in df_p.index:
            p_row = df_p.loc[idx]
            rec = p_row["recording_name"]
            old = p_row["bin_size"]
            if not (pd.isna(derived) and pd.isna(old)) and old != derived:
                self.dict_bins.pop(rec, None)
                self.dict_outputs.pop(rec, None)
                path_bin = self.dict_folders["cache"] / f"{rec}_bin.parquet"
                if path_bin.exists():
                    path_bin.unlink()
                    print(f"trigger_set_bin_size_all: invalidated bin cache for '{rec}'")
            df_p.at[idx, "bin_size"] = derived
        self.set_df_project(df_p)
        display = "0" if pd.isna(derived) else str(derived)
        self.lineEdit_bin_size.setText(display)
        self.recalculate()

    def triggerToggleProjectTable(self, checked=None):
        self.usage("triggerToggleProjectTable")
        if hasattr(self, "tableProj"):
            if type(checked) == bool:
                self.uistate.project.detailedProjectTable = checked
            else:
                self.uistate.project.detailedProjectTable = not self.uistate.project.detailedProjectTable
            self.formatTableLayout()
            if hasattr(self, "actionToggleProjectTable"):
                self.actionToggleProjectTable.setChecked(self.uistate.project.detailedProjectTable)
            self.uistate.save_cfg(projectfolder=self.dict_folders.get("project"))

    def triggerToggleTimetable(self, checked=None):
        self.usage("triggerToggleTimetable")
        if hasattr(self, "tableStim"):
            if type(checked) == bool:
                self.uistate.project.detailedTimetable = checked
            else:
                self.uistate.project.detailedTimetable = not self.uistate.project.detailedTimetable
            dft = None
            if self.uistate.plot.list_idx_select_recs:
                prow = self.get_prow(self.uistate.plot.list_idx_select_recs[0])
                if prow is not None:
                    dft = self.get_dft(prow)

            if dft is None:
                dft = pd.DataFrame([self.uistate.project.default_dict_t])

            self.formatTableStimLayout(dft)

            if hasattr(self, "actionToggleTimetable"):
                self.actionToggleTimetable.setChecked(self.uistate.project.detailedTimetable)
            self.uistate.save_cfg(projectfolder=self.dict_folders.get("project"))

    def triggerRefresh(self):
        self.usage("refresh graphs")
        selection = self.uistate.plot.list_idx_select_recs
        self.recalculate()
        self.uistate.plot.list_idx_select_recs = selection
        self.tableUpdate(restore_selection=True)  # centralized restore (no manual clearSelection)
        self.tableProjSelectionChanged()

    def triggerDarkmode(self):
        self.uistate.darkmode = not self.uistate.darkmode
        self.usage(f"triggerDarkmode set to {self.uistate.darkmode}")
        self.write_bw_cfg()
        self.darkmode()

    def triggerShowHeatmap(self):
        self.usage("triggerShowHeatmap")
        self.toggleHeatmap()

    def triggerShowTimetable(self, checked=None):
        self.usage("triggerShowTimetable")
        if type(checked) == bool:
            self.uistate.project.showTimetable = checked
        else:
            self.uistate.project.showTimetable = not self.uistate.project.showTimetable

        if hasattr(self, "actionTimetable"):
            self.actionTimetable.setChecked(self.uistate.project.showTimetable)

        self.setTableStimVisibility(self.uistate.project.showTimetable)

        if self.uistate.plot.dict_rec_show:
            self.tableProjSelectionChanged()
        self.uistate.save_cfg(projectfolder=self.dict_folders["project"])
        self.write_bw_cfg()

    # (Export logic in ExportMixin)

    def triggerRenameRecording(self):
        self.usage("triggerRenameRecording")
        self.renameRecording()

    def triggerClearGroups(self):
        self.usage("triggerClearGroups")
        if self.uistate.plot.list_idx_select_recs:
            self.clearGroupsByRow(self.uistate.plot.list_idx_select_recs)
            self.tableUpdate(restore_selection=True)
            self.mouseoverUpdate()
        else:
            print("No files selected.")

    def triggerEditGroups(self):  # Open groups UI (not built)
        self.usage("triggerEditGroups")
        # Placeholder: For now, delete all buttons and groups
        self.group_controls_remove()
        self.group_remove()
        self.tableUpdate(restore_selection=True)
        self.mouseoverUpdate()

    def triggerNewGroup(self):
        self.usage("triggerNewGroup")
        self.group_new()

    def triggerRemoveLastGroup(self):
        self.usage("triggerRemoveLastGroup")
        self.group_remove_last()

    def triggerRemoveLastEmptyGroup(self):
        self.usage("triggerRemoveLastEmptyGroup")
        self.group_remove_last_empty()

    def triggerAddToSet(self):
        self.usage("triggerAddToSet")
        self.add_to_data_set()

    def triggerDelete(self):
        self.usage("triggerDelete")
        self.deleteSelectedRows()

    def triggerRenameProject(self):  # renameProject
        self.usage("triggerRenameProject")
        self.inputProjectName.setReadOnly(False)
        self.inputProjectName.selectAll()  # Select all text
        self.inputProjectName.setFocus()  # Set focus
        try:  # Only disconnect if connected
            self.inputProjectName.editingFinished.disconnect()
        except TypeError:
            pass  # Ignore the TypeError that is raised when the signal isn't connected to any slots
        finally:
            self.inputProjectName.editingFinished.connect(self.renameProject)

    def triggerNewProject(self):
        self.usage("triggerNewProject")
        self.newProject()

    def triggerOpenProject(self):  # open folder selector dialog
        self.usage("triggerOpenProject")
        self.dialog = QtWidgets.QDialog()
        print(f"self.projects_folder: {self.projects_folder}")
        str_projectfolder = str(
            QtWidgets.QFileDialog.getExistingDirectory(
                self.dialog,
                "Open Directory",
                str(self.projects_folder),
                QtWidgets.QFileDialog.ShowDirsOnly | QtWidgets.QFileDialog.DontResolveSymlinks | QtWidgets.QFileDialog.DontUseNativeDialog,
            )
        )
        logger.debug("Received projectfolder: %s", str_projectfolder)
        print(f"Received projectfolder: {str_projectfolder}")
        projectpath = Path(str_projectfolder) / "project.brainwash"
        if projectpath.exists():
            logger.debug("Found project %s, loading...", str_projectfolder)
            print(f"Found project {str_projectfolder}, loading...")
            self.openProject(str_projectfolder)
        else:
            logger.warning("No project found in %s", str_projectfolder)
            print(f"No project found in {str_projectfolder}")

    def triggerReanalyze(self):
        self.usage("triggerReanalyze")
        selection = self.uistate.plot.list_idx_select_recs
        self.reanalyze_recordings()
        self.uistate.plot.list_idx_select_recs = selection
        self.tableUpdate(restore_selection=True)  # centralized restore (no manual clearSelection)
        self.tableProjSelectionChanged()

    def triggerAddSelectionToTestSet(self):
        self.usage("triggerAddSelectionToTestSet")
        self.add_to_data_set()

    def triggerRemoveLastTestSet(self):
        self.usage("triggerRemoveLastTestSet")
        self.testset_remove_last()

    def triggerClearTestSets(self):
        self.usage("triggerClearTestSets")
        while self.dd_testsets:
            self.testset_remove_last()

    def triggerSetGain(self):
        self.usage("triggerSetGain")
        selection = self.uistate.plot.list_idx_select_recs
        if not selection:
            print("SetGain: no recordings selected.")
            return

        df_p = self.get_df_project()
        gains = df_p.loc[selection, "gain"].dropna().unique()
        current = str(gains[0]) if len(gains) == 1 else "-"
        n = len(selection)
        noun = "recording" if n == 1 else "recordings"

        dlg = QtWidgets.QDialog()
        dlg.setWindowTitle("Set Gain")
        dlg.setFixedSize(300, 130)
        layout = QtWidgets.QVBoxLayout(dlg)

        label = QtWidgets.QLabel(f"{n} {noun} selected")
        layout.addWidget(label)

        line_edit = QtWidgets.QLineEdit(current)
        line_edit.selectAll()
        layout.addWidget(line_edit)

        buttons = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel,
            QtCore.Qt.Horizontal,
        )
        buttons.accepted.connect(dlg.accept)
        buttons.rejected.connect(dlg.reject)
        layout.addWidget(buttons)

        line_edit.setFocus()
        if dlg.exec_() != QtWidgets.QDialog.Accepted:
            return

        raw = line_edit.text().strip()
        try:
            new_gain = float(raw.replace(",", "."))
        except ValueError:
            print(f"SetGain: '{raw}' is not a valid number.")
            return

        df_p.loc[selection, "gain"] = new_gain
        self.set_df_project(df_p)
        print(f"SetGain: set gain={new_gain} on {n} {noun}.")
        self.tableUpdate(restore_selection=True)  # preserve selection after gain change
        self.reanalyze_recordings()

    def triggerSetSweepHz(self):
        self.usage("triggerSetSweepHz")
        selection = self.uistate.plot.list_idx_select_recs
        if not selection:
            print("SetSweepHz: no recordings selected.")
            return

        df_p = self.get_df_project()
        n = len(selection)
        noun = "recording" if n == 1 else "recordings"

        existing = df_p.loc[selection, "sweep_hz"].dropna().unique()
        current = f"{existing[0]:.4g}" if len(existing) == 1 else ""

        dlg = QtWidgets.QDialog()
        dlg.setWindowTitle("Set Sweep Hz")
        dlg.setFixedSize(300, 130)
        layout = QtWidgets.QVBoxLayout(dlg)

        label = QtWidgets.QLabel(f"{n} {noun} selected")
        layout.addWidget(label)

        line_edit = QtWidgets.QLineEdit(current)
        line_edit.setPlaceholderText("e.g. 0.1")
        line_edit.selectAll()
        layout.addWidget(line_edit)

        buttons = QtWidgets.QDialogButtonBox(
            QtWidgets.QDialogButtonBox.Ok | QtWidgets.QDialogButtonBox.Cancel,
            QtCore.Qt.Horizontal,
        )
        buttons.accepted.connect(dlg.accept)
        buttons.rejected.connect(dlg.reject)
        layout.addWidget(buttons)

        line_edit.setFocus()
        if dlg.exec_() != QtWidgets.QDialog.Accepted:
            return

        raw = line_edit.text().strip()
        try:
            new_hz = float(raw.replace(",", "."))
            if new_hz <= 0:
                raise ValueError
        except ValueError:
            print(f"SetSweepHz: '{raw}' is not a valid positive number.")
            return

        df_p.loc[selection, "sweep_hz"] = new_hz
        # Remove "default Hz" pipe-flag from status for each updated row
        for idx in selection:
            flags = [f for f in str(df_p.at[idx, "status"]).split("|") if f != "default Hz"]
            df_p.at[idx, "status"] = "|".join(flags)
        self.set_df_project(df_p)
        print(f"SetSweepHz: set sweep_hz={new_hz} on {n} {noun}.")
        self.tableUpdate(restore_selection=True)  # preserve selection after sweep_hz change
        self.update_experiment_type_radio_buttons()
        for idx in selection:
            self.uiplot.unPlot(rec_ID=df_p.loc[idx, "ID"])
        self.graphUpdate()

    # (See SweepOpsMixin for sweep ops)

    # (recalculate in DataFrameMixin)

    def update_amp_lineEdits(self):
        if not self.uistate.plot.list_idx_select_recs:
            return

        selected_EPSP_hws = set()
        selected_volley_hws = set()

        for idx_rec in self.uistate.plot.list_idx_select_recs:
            prow = self.get_prow(idx_rec)
            df_t = self.get_dft(prow)
            if df_t is None or (hasattr(df_t, "empty") and df_t.empty):
                continue

            stims_to_check = self.uistate.plot.list_idx_select_stims if self.uistate.plot.list_idx_select_stims else [0]

            for idx_stim in stims_to_check:
                if idx_stim < len(df_t):
                    selected_EPSP_hws.add(df_t.iloc[idx_stim]["t_EPSP_amp_halfwidth"] * 1000)
                    selected_volley_hws.add(df_t.iloc[idx_stim]["t_volley_amp_halfwidth"] * 1000)

        self.connectUIstate(disconnect=True)

        if len(selected_EPSP_hws) == 1:
            self.lineEdit_EPSP_amp_halfwidth.setText(f"{selected_EPSP_hws.pop():g}")
        else:
            self.lineEdit_EPSP_amp_halfwidth.setText("")

        if len(selected_volley_hws) == 1:
            self.lineEdit_volley_amp_halfwidth.setText(f"{selected_volley_hws.pop():g}")
        else:
            self.lineEdit_volley_amp_halfwidth.setText("")

        self.connectUIstate(disconnect=False)

    def update_stim_buttons(self):
        if hasattr(self, "pushButton_stim_add"):
            has_selection = self.uistate.plot.x_select.get("mean_start") is not None
            self.pushButton_stim_add.setEnabled(has_selection)
            # Optional visual styling cue for disabled state if generic qt css doesn't apply well
            if has_selection:
                self.pushButton_stim_add.setStyleSheet("")
            else:
                self.pushButton_stim_add.setStyleSheet("color: gray;")

        if hasattr(self, "pushButton_stim_remove"):
            if self.tableStimModel and self.tableStimModel.rowCount(None) == 0:
                self.pushButton_stim_remove.setEnabled(False)
                self.pushButton_stim_remove.setStyleSheet("color: gray;")
            else:
                self.pushButton_stim_remove.setEnabled(True)
                self.pushButton_stim_remove.setStyleSheet("")

    def update_slope_lineEdits(self):
        if not self.uistate.plot.list_idx_select_recs:
            return

        selected_EPSP_ws = set()
        selected_volley_ws = set()

        for idx_rec in self.uistate.plot.list_idx_select_recs:
            prow = self.get_prow(idx_rec)
            df_t = self.get_dft(prow)
            if df_t is None or (hasattr(df_t, "empty") and df_t.empty):
                continue

            stims_to_check = self.uistate.plot.list_idx_select_stims if self.uistate.plot.list_idx_select_stims else [0]

            for idx_stim in stims_to_check:
                if idx_stim < len(df_t):
                    selected_EPSP_ws.add(df_t.iloc[idx_stim]["t_EPSP_slope_width"] * 1000)
                    selected_volley_ws.add(df_t.iloc[idx_stim]["t_volley_slope_width"] * 1000)

        self.connectUIstate(disconnect=True)

        if len(selected_EPSP_ws) == 1:
            self.lineEdit_EPSP_slope_width.setText(f"{selected_EPSP_ws.pop():g}")
        else:
            self.lineEdit_EPSP_slope_width.setText("")

        if len(selected_volley_ws) == 1:
            self.lineEdit_volley_slope_width.setText(f"{selected_volley_ws.pop():g}")
        else:
            self.lineEdit_volley_slope_width.setText("")

        self.connectUIstate(disconnect=False)

    def editSlopeWidth(self, lineEdit):
        lineEditName = lineEdit.objectName()
        self.usage(f"editSlopeWidth {lineEditName}")
        try:
            num = max(0, float(lineEdit.text().replace(",", ".")))
        except ValueError:
            self.update_slope_lineEdits()
            return

        val_in_seconds = num / 1000

        for idx_rec in self.uistate.plot.list_idx_select_recs:
            prow = self.get_prow(idx_rec)
            df_t = self.get_dft(prow)
            stims_to_edit = self.uistate.plot.list_idx_select_stims if self.uistate.plot.list_idx_select_stims else [0]

            if lineEditName == "lineEdit_EPSP_slope_width":
                if df_t["t_EPSP_slope_width"].dtype != "float64":
                    df_t["t_EPSP_slope_width"] = df_t["t_EPSP_slope_width"].astype("float64")
                if "t_EPSP_slope_end" in df_t.columns and df_t["t_EPSP_slope_end"].dtype != "float64":
                    df_t["t_EPSP_slope_end"] = df_t["t_EPSP_slope_end"].astype("float64")
                if "t_EPSP_slope_halfwidth" in df_t.columns and df_t["t_EPSP_slope_halfwidth"].dtype != "float64":
                    df_t["t_EPSP_slope_halfwidth"] = df_t["t_EPSP_slope_halfwidth"].astype("float64")
            elif lineEditName == "lineEdit_volley_slope_width":
                if df_t["t_volley_slope_width"].dtype != "float64":
                    df_t["t_volley_slope_width"] = df_t["t_volley_slope_width"].astype("float64")
                if "t_volley_slope_end" in df_t.columns and df_t["t_volley_slope_end"].dtype != "float64":
                    df_t["t_volley_slope_end"] = df_t["t_volley_slope_end"].astype("float64")
                if "t_volley_slope_halfwidth" in df_t.columns and df_t["t_volley_slope_halfwidth"].dtype != "float64":
                    df_t["t_volley_slope_halfwidth"] = df_t["t_volley_slope_halfwidth"].astype("float64")

            for idx_stim in stims_to_edit:
                if idx_stim < len(df_t):
                    if lineEditName == "lineEdit_EPSP_slope_width":
                        df_t.at[idx_stim, "t_EPSP_slope_width"] = val_in_seconds
                        df_t.at[idx_stim, "t_EPSP_slope_end"] = df_t.at[idx_stim, "t_EPSP_slope_start"] + val_in_seconds
                        df_t.at[idx_stim, "t_EPSP_slope_halfwidth"] = val_in_seconds / 2.0
                    elif lineEditName == "lineEdit_volley_slope_width":
                        df_t.at[idx_stim, "t_volley_slope_width"] = val_in_seconds
                        df_t.at[idx_stim, "t_volley_slope_end"] = df_t.at[idx_stim, "t_volley_slope_start"] + val_in_seconds
                        df_t.at[idx_stim, "t_volley_slope_halfwidth"] = val_in_seconds / 2.0

            self.set_dft(prow["recording_name"], df_t)

        self.recalculate(selection=self.uistate.plot.list_idx_select_recs)
        self.update_slope_lineEdits()

    def editAmpHalfwidth(self, lineEdit):
        lineEditName = lineEdit.objectName()
        self.usage(f"editAmpHalfwidth {lineEditName}")
        try:
            num = max(0, float(lineEdit.text().replace(",", ".")))
        except ValueError:
            self.update_amp_lineEdits()
            return

        val_in_seconds = num / 1000

        for idx_rec in self.uistate.plot.list_idx_select_recs:
            prow = self.get_prow(idx_rec)
            df_t = self.get_dft(prow)
            stims_to_edit = self.uistate.plot.list_idx_select_stims if self.uistate.plot.list_idx_select_stims else [0]

            if lineEditName == "lineEdit_EPSP_amp_halfwidth" and df_t["t_EPSP_amp_halfwidth"].dtype != "float64":
                df_t["t_EPSP_amp_halfwidth"] = df_t["t_EPSP_amp_halfwidth"].astype("float64")
            elif lineEditName == "lineEdit_volley_amp_halfwidth" and df_t["t_volley_amp_halfwidth"].dtype != "float64":
                df_t["t_volley_amp_halfwidth"] = df_t["t_volley_amp_halfwidth"].astype("float64")

            for idx_stim in stims_to_edit:
                if idx_stim < len(df_t):
                    if lineEditName == "lineEdit_EPSP_amp_halfwidth":
                        df_t.at[idx_stim, "t_EPSP_amp_halfwidth"] = val_in_seconds
                    elif lineEditName == "lineEdit_volley_amp_halfwidth":
                        df_t.at[idx_stim, "t_volley_amp_halfwidth"] = val_in_seconds

            self.set_dft(prow["recording_name"], df_t)

        self.recalculate(selection=self.uistate.plot.list_idx_select_recs)
        self.update_amp_lineEdits()

    def editSort(self, lineEdit, start, end, request="int"):
        def str2num(text):
            try:
                if request == "float":
                    return max(0, float(text.replace(",", ".")))
                else:
                    return max(0, int(text.replace(",", ".")))
            except ValueError:
                return 0

        def num2str(num):
            if request == "float":
                return str(max(0, float(num)))
            else:
                return str(max(0, int(num)))

        num = str2num(lineEdit.text())
        if lineEdit.objectName() == start.objectName():
            pair = str2num(end.text())
        else:
            pair = str2num(start.text())
        low, high = min(num, pair), max(num, pair)
        start.setText(num2str(low))
        end.setText(num2str(high))
        return low, high

    def editImportOptions(self, lineEdit):
        self.usage("editImportOptions")
        lineEditName = lineEdit.objectName()
        try:
            text = lineEdit.text().replace(",", ".")
            num = max(0, float(text))
        except ValueError:
            num = 0
        lineEdit.setText(str(num))
        if lineEditName == "lineEdit_split_at_time":
            self.uistate.project.lineEdit["split_at_time"] = float(lineEdit.text()) / 1000.0
            if self.uistate.project.lineEdit["split_at_time"] is not None and self.uistate.project.lineEdit["split_at_time"] != 0:
                self.uistate.project.checkBox["splitOddEven"] = False
                self.checkBox_splitOddEven.setChecked(False)
        elif lineEditName == "lineEdit_import_gain":
            self.uistate.project.lineEdit["import_gain"] = float(lineEdit.text())

    def editMeanSelectRange(self, lineEdit):
        self.usage("editMeanSelectRange")
        low, high = self.editSort(
            lineEdit,
            start=self.lineEdit_mean_selection_start,
            end=self.lineEdit_mean_selection_end,
            request="float",
        )
        # lineEdits display ms; self.uistate stores s
        self.uistate.plot.x_select["mean_start"] = low / 1000.0
        self.uistate.plot.x_select["mean_end"] = high / 1000.0 if high else None
        self.uiplot.xSelect(self.uistate.plot.axm.figure.canvas)

    def editSweepSelectRange(self, lineEdit):
        self.usage("editSweepSelectRange")
        low, high = self.editSort(
            lineEdit,
            start=self.lineEdit_sweeps_range_from,
            end=self.lineEdit_sweeps_range_to,
        )
        self.uistate.plot.x_select["output_start"], self.uistate.plot.x_select["output_end"] = low, high
        self.uistate.plot.x_select["output"] = set(range(low, high + 1))
        self.uiplot.xSelect(self.uistate.plot.ax1.figure.canvas)
        self.uiplot.update_axe_mean()

    def editNormRange(self, lineEdit):
        self.usage("editNormRange")
        _ = self.editSort(
            lineEdit,
            start=self.lineEdit_norm_EPSP_start,
            end=self.lineEdit_norm_EPSP_end,
        )
        # TODO: show selection on graph

    def editBinSize(self, lineEdit):
        self.usage("editBinSize")
        text = lineEdit.text().strip()
        if not text:
            return  # blank = mixed-selection sentinel; do nothing
        try:
            num = int(text.replace(",", "."))
        except ValueError:
            num = 0
        derived = float("nan") if num <= 1 else float(num)
        display = "0" if math.isnan(derived) else str(int(derived))
        lineEdit.setText(display)
        print(f"editBinSize: num={num} -> derived={derived}")

        # Determine scope: selected recordings, or all if none selected.
        df_p = self.get_df_project()
        if self.uistate.plot.list_idx_select_recs:
            indices = self.uistate.plot.list_idx_select_recs
        else:
            indices = list(df_p.index)

        for idx in indices:
            p_row = df_p.loc[idx]
            rec = p_row["recording_name"]
            old = p_row["bin_size"]
            if pd.isna(derived) and pd.isna(old):
                changed = False
            elif pd.isna(derived) or pd.isna(old):
                changed = True
            else:
                changed = old != derived
            if changed:
                self.dict_bins.pop(rec, None)
                self.dict_outputs.pop(rec, None)
                path_bin = self.dict_folders["cache"] / f"{rec}_bin.parquet"
                if path_bin.exists():
                    path_bin.unlink()
                    print(f"editBinSize: invalidated bin cache for '{rec}'")
            df_p.at[idx, "bin_size"] = derived
        self.set_df_project(df_p)
        self.uistate.save_cfg(projectfolder=self.dict_folders["project"])
        self.recalculate()

    def copy_dft(self):
        # get selected dft(s) and copy to clipboard
        if len(self.uistate.plot.list_idx_select_recs) < 1:
            print("copy_dft: nothing selected.")
            return
        selected_dfts = pd.DataFrame()
        for rec in self.uistate.plot.list_idx_select_recs:
            p_row = self.get_df_project().loc[rec]
            dft = self.get_dft(p_row)
            dft.insert(0, "recording_name", p_row["recording_name"])
            selected_dfts = pd.concat([selected_dfts, dft], ignore_index=True)
        selected_dfts.to_clipboard(index=False)

    def copy_output(self):
        if len(self.uistate.plot.list_idx_select_recs) < 1:
            print("copy_output: nothing selected.")
            return
        selected_outputs = pd.DataFrame()
        is_pp = self.uistate.experiment.experiment_type == "PP"

        for rec in self.uistate.plot.list_idx_select_recs:
            p_row = self.get_df_project().loc[rec]
            output = self.get_dfoutput(p_row).copy()
            output.insert(0, "recording_name", p_row["recording_name"])
            output.insert(1, "gain", p_row["gain"])

            if is_pp:
                out_sweeps = output[output["sweep"].notna()]
                out1 = out_sweeps[out_sweeps["stim"] == 1].set_index("sweep")
                out2 = out_sweeps[out_sweeps["stim"] == 2].set_index("sweep")
                common_sweeps = out1.index.intersection(out2.index).dropna()

                if not common_sweeps.empty:
                    o1 = out1.loc[common_sweeps]
                    o2 = out2.loc[common_sweeps]

                    pp_df = pd.DataFrame()
                    pp_df["recording_name"] = o1["recording_name"]
                    pp_df["gain"] = o1["gain"]
                    pp_df["sweep"] = common_sweeps

                    aspects = ["EPSP_amp", "EPSP_slope", "volley_amp", "volley_slope"]
                    for aspect in aspects:
                        if aspect in o1.columns and aspect in o2.columns:
                            v1 = o1[aspect].values.astype(float)
                            v2 = o2[aspect].values.astype(float)
                            with warnings.catch_warnings():
                                warnings.simplefilter("ignore")
                                ppr = plot_series.compute_ppr_percent(v1, v2)
                            pp_df[f"PPR_{aspect}"] = ppr

                    selected_outputs = pd.concat([selected_outputs, pp_df], ignore_index=True)
            else:
                selected_outputs = pd.concat([selected_outputs, output], ignore_index=True)

        selected_outputs.to_clipboard(index=False)

    def stimDetect(self):
        if not self.uistate.plot.list_idx_select_recs:
            print("No files selected.")
            return
        df_p = self.get_df_project()
        for index in self.uistate.plot.list_idx_select_recs:
            p_row = df_p.loc[index]
            old_df_t = self.get_dft(p_row)
            rec_name = p_row["recording_name"]
            rec_ID = p_row["ID"]
            stims = p_row["stims"]
            if p_row["sweeps"] == "...":
                print(f"{rec_name} not parsed yet.")
                continue
            print(f"Detecting stims for {rec_name}")
            if self.uistate.plot.x_select["mean_start"] is not None:
                print(f" - range: {self.uistate.plot.x_select['mean_start']} to {self.uistate.plot.x_select['mean_end']}")
            dfmean = self.get_dfmean(p_row)
            if self.uistate.plot.x_select["mean_start"] is not None and self.uistate.plot.x_select["mean_end"] is not None:
                dfmean_range = dfmean[
                    (dfmean["time"] >= self.uistate.plot.x_select["mean_start"]) & (dfmean["time"] <= self.uistate.plot.x_select["mean_end"])
                ].reset_index(drop=True)
            else:
                dfmean_range = dfmean
            default_dict_t = self.uistate.project.default_dict_t.copy()  # Default sizes
            print(f"stimDetect: {rec_name} calling find_events within range:\n{self.uistate.plot.x_select}")
            new_df_t = analysis.find_events(
                dfmean=dfmean_range,
                default_dict_t=default_dict_t,
                filter=p_row["filter"],
                verbose=False,
            )
            if new_df_t is None:
                print(f"StimDetect: No stims found for {rec_name}.")
                continue
            if self.uistate.project.checkBox["timepoints_per_stim"] or stims == 1:
                self.set_dft(rec_name, new_df_t)
            else:
                dfoutput = self.get_dfoutput(p_row)
                print(f"stimDetect: {rec_name} calling set_uniformTimepoints with df_t:\n{new_df_t}")
                # list_obsolete_stim_idx: a list of idx of old_df_t rows, that have a t_stim that isn't in new_df_t
                list_obsolete_stim_idx = [i for i, row in old_df_t.iterrows() if row["t_stim"] not in new_df_t["t_stim"].values]
                if list_obsolete_stim_idx:
                    print(f"Obsolete stims: {list_obsolete_stim_idx}")
                    for idx in list_obsolete_stim_idx:
                        dfoutput = dfoutput.drop(idx)
                        print(f" - removed idx {idx} from dfoutput")
                    dfoutput = dfoutput.reset_index(drop=True)
                    dfoutput["stim"] = new_df_t["stim"]
                self.set_uniformTimepoints(p_row=p_row, dft=new_df_t, dfoutput=dfoutput)
            df_p.loc[p_row["ID"] == df_p["ID"], "stims"] = len(new_df_t)
            self.set_df_project(df_p)
            self.uiplot.unPlot(rec_ID)
            dfoutput = self.get_dfoutput(p_row)
            self.persistOutput(p_row["recording_name"], dfoutput, p_row=p_row)
            self.uiplot.addRow(p_row, new_df_t, dfmean, self.V2mV(dfoutput))
        self.uistate.plot.list_idx_select_stims = [0]
        p_row = df_p.loc[self.uistate.plot.list_idx_select_recs[0]]
        df_t = self.get_dft(p_row)
        self.tableStimModel.setData(df_t)
        self.formatTableStimLayout(df_t)
        self.tableStim.selectRow(0)
        # unplot and replot all affected recordings
        self.update_show(reset=True)
        self.mouseoverUpdate()

    def checkBox_splitOddEven_changed(self, state):
        self.uistate.project.checkBox["splitOddEven"] = state == 2
        logger.debug("checkBox_splitOddEven_changed: %s", state)
        print(f"checkBox_splitOddEven_changed: {state}")

    def checkBox_timepoints_per_stim_changed(self, state):
        self.uistate.project.checkBox["timepoints_per_stim"] = state == 2
        print(f"checkBox_timepoints_per_stim_changed: {state}")
        if state == 0:
            self.set_uniformTimepoints()

    def checkBox_is_group_sample_changed(self, state):
        self.uistate.project.checkBox["is_group_sample"] = state == 2
        logger.debug("checkBox_is_group_sample_changed: %s", state)
        print(f"checkBox_is_group_sample_changed: {state}")
        if len(self.uistate.plot.list_idx_select_recs) != 1:
            return
        prow = self.get_prow()
        if prow is None:
            return
        rec_ID = prow["ID"]
        rec_str = str(rec_ID)
        target = rec_str if (state == 2) else None
        self.set_group_sample(target)
        self.graphRefresh()
        self.update_sample_checkbox()

    # tableFormat (and other table methods) moved to TableMixin in ui_table.py


# Root functions


def get_signals(source):
    cls = source if isinstance(source, type) else type(source)
    signal = type(QtCore.pyqtSignal())
    print("get_signals:")
    for subcls in cls.mro():
        clsname = f"{subcls.__module__}.{subcls.__name__}"
        for key, aspect in sorted(vars(subcls).items()):
            if isinstance(aspect, signal):
                print(f"{key} [{clsname}]")


# Mainguard
if __name__ == "__main__":
    _config = ui_widgets.Config()
    print(f"\n\n{_config.program_name} {_config.version}\n")
    app = QtWidgets.QApplication(
        sys.argv
    )  # "QtWidgets.QApplication(sys.argv) appears to cause Qt: Session management error: None of the authentication protocols specified are supported"
    main_window = QtWidgets.QMainWindow()
    uisub = UIsub(main_window)
    main_window.show()
    sys.exit(app.exec_())
