# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bwmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(783, 592)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputProjectName = QtWidgets.QLineEdit(self.centralwidget)
        self.inputProjectName.setGeometry(QtCore.QRect(10, 10, 191, 22))
        self.inputProjectName.setObjectName("inputProjectName")
        self.pushButtonAddData = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddData.setGeometry(QtCore.QRect(310, 10, 71, 24))
        self.pushButtonAddData.setObjectName("pushButtonAddData")
        self.pushButtonOpenProject = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOpenProject.setEnabled(False)
        self.pushButtonOpenProject.setGeometry(QtCore.QRect(210, 10, 91, 24))
        self.pushButtonOpenProject.setObjectName("pushButtonOpenProject")
        self.tableMaster = QtWidgets.QTableView(self.centralwidget)
        self.tableMaster.setGeometry(QtCore.QRect(10, 40, 371, 511))
        self.tableMaster.setObjectName("tableMaster")
        self.labelMetadata = QtWidgets.QLabel(self.centralwidget)
        self.labelMetadata.setGeometry(QtCore.QRect(390, 470, 141, 16))
        self.labelMetadata.setObjectName("labelMetadata")
        self.pushButtonSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSelect.setGeometry(QtCore.QRect(720, 10, 51, 24))
        self.pushButtonSelect.setObjectName("pushButtonSelect")
        self.checkPreview = QtWidgets.QCheckBox(self.centralwidget)
        self.checkPreview.setGeometry(QtCore.QRect(630, 10, 77, 21))
        self.checkPreview.setObjectName("checkPreview")
        self.graphData = QtWidgets.QWidget(self.centralwidget)
        self.graphData.setGeometry(QtCore.QRect(390, 40, 381, 191))
        self.graphData.setObjectName("graphData")
        self.graphOutput = QtWidgets.QWidget(self.centralwidget)
        self.graphOutput.setGeometry(QtCore.QRect(390, 260, 381, 201))
        self.graphOutput.setObjectName("graphOutput")
        self.labelMeanGroups = QtWidgets.QLabel(self.centralwidget)
        self.labelMeanGroups.setGeometry(QtCore.QRect(390, 240, 141, 16))
        self.labelMeanGroups.setObjectName("labelMeanGroups")
        self.labelMeanSweep = QtWidgets.QLabel(self.centralwidget)
        self.labelMeanSweep.setGeometry(QtCore.QRect(390, 20, 141, 16))
        self.labelMeanSweep.setObjectName("labelMeanSweep")
        self.tableMetadata = QtWidgets.QTableView(self.centralwidget)
        self.tableMetadata.setGeometry(QtCore.QRect(390, 490, 381, 61))
        self.tableMetadata.setObjectName("tableMetadata")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brainwash 0.1"))
        self.inputProjectName.setText(_translate("MainWindow", "placeholder project name"))
        self.pushButtonAddData.setText(_translate("MainWindow", "Add data"))
        self.pushButtonOpenProject.setText(_translate("MainWindow", "Open project"))
        self.labelMetadata.setText(_translate("MainWindow", "Metadata:"))
        self.pushButtonSelect.setText(_translate("MainWindow", "select"))
        self.checkPreview.setText(_translate("MainWindow", "Preview"))
        self.labelMeanGroups.setText(_translate("MainWindow", "Mean Groups:"))
        self.labelMeanSweep.setText(_translate("MainWindow", "Mean Sweep:"))
