# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bwmain.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 593)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 191, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButtonAddData = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAddData.setGeometry(QtCore.QRect(310, 10, 71, 24))
        self.pushButtonAddData.setObjectName("pushButtonAddData")
        self.pushButton_OpenProject = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_OpenProject.setEnabled(False)
        self.pushButton_OpenProject.setGeometry(QtCore.QRect(210, 10, 91, 24))
        self.pushButton_OpenProject.setObjectName("pushButton_OpenProject")
        self.MasterTableView = QtWidgets.QTableView(self.centralwidget)
        self.MasterTableView.setGeometry(QtCore.QRect(10, 40, 371, 511))
        self.MasterTableView.setObjectName("MasterTableView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 240, 141, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 10, 51, 24))
        self.pushButton.setObjectName("pushButton")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(410, 10, 77, 21))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Brainwash 0.1"))
        self.lineEdit.setText(_translate("MainWindow", "placeholder project name"))
        self.pushButtonAddData.setText(_translate("MainWindow", "Add data"))
        self.pushButton_OpenProject.setText(_translate("MainWindow", "Open project"))
        self.label_2.setText(_translate("MainWindow", "Metadata:"))
        self.pushButton.setText(_translate("MainWindow", "select"))
        self.checkBox.setText(_translate("MainWindow", "Preview"))
