# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bwmeasure.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_measure(object):
    def setupUi(self, measure):
        measure.setObjectName("measure")
        measure.resize(820, 588)
        self.verticalLayoutWidget = QtWidgets.QWidget(measure)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 801, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.measure_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.measure_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.measure_verticalLayout.setObjectName("measure_verticalLayout")
        self.measure_graph_mean = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.measure_graph_mean.setMinimumSize(QtCore.QSize(0, 100))
        self.measure_graph_mean.setObjectName("measure_graph_mean")
        self.measure_verticalLayout.addWidget(self.measure_graph_mean)
        self.measure_info = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.measure_info.setObjectName("measure_info")
        self.measure_verticalLayout.addWidget(self.measure_info)
        self.measure_graph_output = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.measure_graph_output.setMinimumSize(QtCore.QSize(0, 100))
        self.measure_graph_output.setObjectName("measure_graph_output")
        self.measure_verticalLayout.addWidget(self.measure_graph_output)
        self.measure_verticalLayout.setStretch(0, 4)
        self.measure_verticalLayout.setStretch(1, 1)
        self.measure_verticalLayout.setStretch(2, 2)

        self.retranslateUi(measure)
        QtCore.QMetaObject.connectSlotsByName(measure)

    def retranslateUi(self, measure):
        _translate = QtCore.QCoreApplication.translate
        measure.setWindowTitle(_translate("measure", "Placeholder Window Title"))
