# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bwmeasure.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_measure_window(object):
    def setupUi(self, measure_window):
        measure_window.setObjectName("measure_window")
        measure_window.resize(800, 600)
        measure_window.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(measure_window)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.measure_verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.measure_verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.measure_verticalLayout.setObjectName("measure_verticalLayout")
        self.measure_graph_mean = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.measure_graph_mean.setMinimumSize(QtCore.QSize(0, 100))
        self.measure_graph_mean.setObjectName("measure_graph_mean")
        self.measure_verticalLayout.addWidget(self.measure_graph_mean)
        self.measure_info = QtWidgets.QTableView(self.verticalLayoutWidget)
        self.measure_info.setObjectName("measure_info")
        self.measure_verticalLayout.addWidget(self.measure_info)
        self.measure_graph_output = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.measure_graph_output.setMinimumSize(QtCore.QSize(0, 100))
        self.measure_graph_output.setObjectName("measure_graph_output")
        self.measure_verticalLayout.addWidget(self.measure_graph_output)
        self.measure_verticalLayout.setStretch(0, 4)
        self.measure_verticalLayout.setStretch(1, 1)
        self.measure_verticalLayout.setStretch(2, 2)
        measure_window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(measure_window)
        self.statusbar.setObjectName("statusbar")
        measure_window.setStatusBar(self.statusbar)

        self.retranslateUi(measure_window)
        QtCore.QMetaObject.connectSlotsByName(measure_window)

    def retranslateUi(self, measure_window):
        _translate = QtCore.QCoreApplication.translate
        measure_window.setWindowTitle(_translate("measure_window", "placeholder_name_of_recording"))
