name: Build with cx_Freeze

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        #, windows-latest]
        python-version: ["3.12"]

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      # Jonathan's addition from Grok
      - name: List files
        run: ls -la

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Install patchelf on Linux (required for cx_Freeze)
      - name: Install patchelf (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y patchelf

      # Build the executable
      - name: Build with cx_Freeze
        working-directory: ./src  # Adjust to your subdirectory
        env:
          APPI_COMPRESSION: gzip  # Force gzip to avoid zstd
        run: python setup.py bdist_appimage --silent
        # run: python setup.py build_exe

      - name: List files for debugging
        if: matrix.os == 'ubuntu-latest'
        run: |
          ls -R src/dist/ || echo "src/dist/ not found"
          ls -R build/ || echo "build/ not found"
        shell: bash

      # Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executable-${{ matrix.os }}
          path: src/dist/*
